// This file was automatically generated by the Evolution Generator.
// The Evolution Generator is used to automate the creation of consistent, reliable code.
// Any changes made to this file will be overwritten.

import { isSectionCompleted } from 'evolution-common/lib/services/questionnaire/sections/navigationHelpers';
import { SectionConfig } from 'evolution-common/lib/services/questionnaire/types';
import { widgetsNames } from './widgetsNames';
import { getSelfRespondentWithDisabilitiesAndTrip } from '../../common/customHelpers';
import { allPersonsTripDiariesCompleted } from '../../common/helper';
import { isPartialSample } from '../../common/commonHelpers';
import { getResponse } from 'evolution-common/lib/utils/helpers';
import { _isBlank } from 'chaire-lib-common/lib/utils/LodashExtensions';

export const currentSectionName: string = 'barriersDisability';
const previousSectionName: SectionConfig['previousSection'] = 'longDistance';
const nextSectionName: SectionConfig['nextSection'] = 'selectFreqPerson';

const visibleEps = ['householdType', 'omission', 'paidParking', 'respect'];

// Config for the section
export const sectionConfig: SectionConfig = {
    previousSection: previousSectionName,
    nextSection: nextSectionName,
    title: {
        fr: 'Freins au TC - transport adapté',
        en: 'Barriers to transit - paratransit'
    },
    navMenu: {
        type: 'hidden',
        parentSection: 'end'
    },
    widgets: widgetsNames,
    // Do some actions before the section is loaded
    // Allow to click on the section menu
    enableConditional: function (interview) {
        // FIXME Wrong condition but it works for now. Evolution should support blocks of optional sections See https://github.com/chairemobilite/evolution/issues/1634
        return allPersonsTripDiariesCompleted(interview);
    },
    // Determine if the current section is completed
    completionConditional: function (interview) {
        // Completed if partial sample is not one of the applicable or actually
        // completed or if there is no self respondent with disability
        return (
            !isPartialSample(interview, visibleEps) ||
            getSelfRespondentWithDisabilitiesAndTrip(interview).length === 0 ||
            isSectionCompleted({ interview, sectionName: currentSectionName })
        );
    },
    onSectionEntry: (interview) => {
        const selfRespondentsWithTrips = getSelfRespondentWithDisabilitiesAndTrip(interview);
        if (selfRespondentsWithTrips.length > 1) {
            console.log(
                'Barriers to TC section - paratransit: there would have been more than one possibility to answer'
            );
        }

        // If there is already a selected trip and person, make sure it is still valid and do not change
        const currentPersonWithDisability = getResponse(interview, '_barriersDisabilityPersonId');
        const currentTripPath = getResponse(interview, '_barriersDisabilityTripPath');
        if (
            !_isBlank(currentPersonWithDisability) &&
            !_isBlank(currentTripPath) &&
            selfRespondentsWithTrips.find(
                (personTrip) =>
                    personTrip.personId === currentPersonWithDisability && personTrip.tripPath === currentTripPath
            ) !== undefined
        ) {
            return {};
        }

        // Select the first person/trip that applies and reset all previous answers
        const selectedTrip = selfRespondentsWithTrips[0];
        return {
            'response._barriersDisabilityTripPath': selectedTrip.tripPath,
            'response._barriersDisabilityPersonId': selectedTrip.personId,
            'response.barriersDisabilityIsPersonAvailable': undefined,
            'response.barriersDisabilityFrequency': undefined,
            'response.barriersDisabilityReliability': undefined,
            'response.barriersDisabilityWalk': undefined,
            'response.barriersDisabilityTime': undefined,
            'response.barriersDisabilityTransfer': undefined,
            'response.barriersDisabilitySecurity': undefined,
            'response.barriersDisabilityUniversalAccessibility': undefined,
            'response.barriersDisabilityPlanning': undefined,
            'response.barriersDisabilityCourtesy': undefined
        };
    },
    isSectionVisible: (interview) => {
        // Section visible seulement si ep exclusif est est l'un qui inclut
        // disabilities ET qu'il y a au moins une personne auto-répondante avec
        // disabilities ET un déplacement en transport adapté
        if (!isPartialSample(interview, visibleEps)) {
            return false;
        }
        const selfRespondentsWithTrips = getSelfRespondentWithDisabilitiesAndTrip(interview);
        return selfRespondentsWithTrips.length > 0;
    }
};

export default sectionConfig;
