// This file was automatically generated by the Evolution Generator.
// The Evolution Generator is used to automate the creation of consistent, reliable code.
// Any changes made to this file will be overwritten.

import { TFunction } from 'i18next';
import * as defaultInputBase from 'evolution-frontend/lib/components/inputs/defaultInputBase';
import { defaultConditional } from 'evolution-common/lib/services/widgets/conditionals/defaultConditional';
import * as WidgetConfig from 'evolution-common/lib/services/questionnaire/types';
import * as validations from 'evolution-common/lib/services/widgets/validations/validations';
import * as choices from '../../common/choices';
import * as conditionals from '../../common/conditionals';
import * as customConditionals from '../../common/customConditionals';
import * as customLabels from '../../common/customLabels';

export const barriersDisabilitySectionIntro: WidgetConfig.TextWidgetConfig = {
    ...defaultInputBase.infoTextBase,
    path: 'barriersDisabilitySectionIntro',
    containsHtml: true,
    text: (t: TFunction) => t('barriersDisability:barriersDisabilitySectionIntro'),
    conditional: defaultConditional
};

export const barriersDisabilitySectionIntro2: WidgetConfig.TextWidgetConfig = {
    ...defaultInputBase.infoTextBase,
    path: 'barriersDisabilitySectionIntro2',
    containsHtml: true,
    text: (t: TFunction) => t('barriersDisability:barriersDisabilitySectionIntro2'),
    conditional: customConditionals.hasMoreThanOneSelfRespondentCustomConditional
};

export const barriersDisabilityIsPersonAvailable: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'barriersDisabilityIsPersonAvailable',
    twoColumns: false,
    containsHtml: true,
    label: customLabels.barrierDisabilitySelectPersonCustomLabel,
    choices: choices.yesNo,
    conditional: customConditionals.hasMoreThanOneSelfRespondentDefaultYesCustomConditional,
    validations: validations.requiredValidation
};

export const barriersDisabilityTrip: WidgetConfig.TextWidgetConfig = {
    ...defaultInputBase.infoTextBase,
    path: 'barriersDisabilityTrip',
    containsHtml: true,
    text: customLabels.barriersDisabilityTripCustomLabel,
    conditional: conditionals.isBarriersDisabilityTripPersonAvailableConditional
};

export const barriersDisabilityIntro: WidgetConfig.TextWidgetConfig = {
    ...defaultInputBase.infoTextBase,
    path: 'barriersDisabilityIntro',
    containsHtml: true,
    text: (t: TFunction) => t('barriersDisability:barriersDisabilityIntro'),
    conditional: conditionals.isBarriersDisabilityTripPersonAvailableConditional
};

export const barriersDisabilityFrequency: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'barriersDisabilityFrequency',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('barriersDisability:barriersDisabilityFrequency'),
    choices: choices.barriersChoices,
    conditional: conditionals.isBarriersDisabilityTripPersonAvailableConditional,
    validations: validations.optionalValidation
};

export const barriersDisabilityReliability: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'barriersDisabilityReliability',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('barriersDisability:barriersDisabilityReliability'),
    choices: choices.barriersChoices,
    conditional: conditionals.isBarriersDisabilityTripPersonAvailableConditional,
    validations: validations.optionalValidation
};

export const barriersDisabilityWalk: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'barriersDisabilityWalk',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('barriersDisability:barriersDisabilityWalk'),
    choices: choices.barriersChoices,
    conditional: conditionals.isBarriersDisabilityTripPersonAvailableConditional,
    validations: validations.optionalValidation
};

export const barriersDisabilityTime: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'barriersDisabilityTime',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('barriersDisability:barriersDisabilityTime'),
    choices: choices.barriersChoices,
    conditional: conditionals.isBarriersDisabilityTripPersonAvailableConditional,
    validations: validations.optionalValidation
};

export const barriersDisabilityTransfer: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'barriersDisabilityTransfer',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('barriersDisability:barriersDisabilityTransfer'),
    choices: choices.barriersChoices,
    conditional: conditionals.isBarriersDisabilityTripPersonAvailableConditional,
    validations: validations.optionalValidation
};

export const barriersDisabilitySecurity: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'barriersDisabilitySecurity',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('barriersDisability:barriersDisabilitySecurity'),
    choices: choices.barriersChoices,
    conditional: conditionals.isBarriersDisabilityTripPersonAvailableConditional,
    validations: validations.optionalValidation
};

export const barriersDisabilityUniversalAccessibility: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'barriersDisabilityUniversalAccessibility',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('barriersDisability:barriersDisabilityUniversalAccessibility'),
    choices: choices.barriersChoices,
    conditional: conditionals.isBarriersDisabilityTripPersonAvailableConditional,
    validations: validations.optionalValidation
};

export const barriersDisabilityPlanning: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'barriersDisabilityPlanning',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('barriersDisability:barriersDisabilityPlanning'),
    choices: choices.barriersChoices,
    conditional: conditionals.isBarriersDisabilityTripPersonAvailableConditional,
    validations: validations.optionalValidation
};

export const barriersDisabilityCourtesy: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'barriersDisabilityCourtesy',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('barriersDisability:barriersDisabilityCourtesy'),
    choices: choices.barriersChoices,
    conditional: conditionals.isBarriersDisabilityTripPersonAvailableConditional,
    validations: validations.optionalValidation
};

export const buttonCompleteBarriersDisabilitySection: WidgetConfig.ButtonWidgetConfig = {
    ...defaultInputBase.buttonNextBase,
    path: 'buttonCompleteBarriersDisabilitySection',
    label: (t: TFunction) => t('barriersDisability:buttonCompleteBarriersDisabilitySection'),
    conditional: defaultConditional
};
