// This file was automatically generated by the Evolution Generator.
// The Evolution Generator is used to automate the creation of consistent, reliable code.
// Any changes made to this file will be overwritten.

import { SectionConfig } from 'evolution-common/lib/services/questionnaire/types';

export const widgetsNames: SectionConfig['widgets'] = [
    'barriersDisabilitySectionIntro',
    'barriersDisabilitySectionIntro2',
    'barriersDisabilityIsPersonAvailable',
    'barriersDisabilityTrip',
    'barriersDisabilityTripMap',
    'barriersDisabilityIntro',
    'barriersDisabilityFrequency',
    'barriersDisabilityReliability',
    'barriersDisabilityWalk',
    'barriersDisabilityTime',
    'barriersDisabilityTransfer',
    'barriersDisabilitySecurity',
    'barriersDisabilityUniversalAccessibility',
    'barriersDisabilityPlanning',
    'barriersDisabilityCourtesy',
    'buttonCompleteBarriersDisabilitySection'
];
