// This file was automatically generated by the Evolution Generator.
// The Evolution Generator is used to automate the creation of consistent, reliable code.
// Any changes made to this file will be overwritten.

import { TFunction } from 'i18next';
import _escape from 'lodash/escape';
import * as defaultInputBase from 'evolution-frontend/lib/components/inputs/defaultInputBase';
import { defaultConditional } from 'evolution-common/lib/services/widgets/conditionals/defaultConditional';
import * as WidgetConfig from 'evolution-common/lib/services/questionnaire/types';
import * as validations from 'evolution-common/lib/services/widgets/validations/validations';
import * as odSurveyHelpers from 'evolution-common/lib/services/odSurvey/helpers';
import * as choices from '../../common/choices';
import * as conditionals from '../../common/conditionals';
import * as customConditionals from '../../common/customConditionals';
import * as customWidgets from './customWidgets';
import * as customChoices from './customChoices';
import * as customHelpPopup from '../../common/customHelpPopup';
import * as customValidations from '../../common/customValidations';
import * as customLabels from '../../common/customLabels';

export const householdMembers = customWidgets.householdMembers;

export const personNickname: WidgetConfig.InputStringType = {
    ...defaultInputBase.inputStringBase,
    path: 'nickname',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('household:personNickname'),
    conditional: customConditionals.hasPersonCount2OrMoreCustomConditional,
    validations: customValidations.uniqueNicknameCustomValidation
};

export const personAge: WidgetConfig.InputStringType = {
    ...defaultInputBase.inputNumberBase,
    path: 'age',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction, interview, path) => {
        const countPersons = odSurveyHelpers.countPersons({ interview });
        return t('household:personAge', {
            count: countPersons
        });
    },
    conditional: defaultConditional,
    validations: validations.ageValidation
};

// If this value is set and sexAssignedAtBirth is not ‘preferNotToAnswer’, it has been automatically set. It may not match the actual gender
export const personGender: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'gender',
    twoColumns: false,
    containsHtml: true,
    customPath: 'genderCustom',
    customChoice: 'custom',
    label: (t: TFunction) => t('household:personGender'),
    choices: choices.maleFemaleCustomPreferNotToAnswer,
    conditional: conditionals.ifAge5orMoreConditional,
    validations: validations.requiredValidation
};

export const personDrivingLicenseOwnership: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'drivingLicenseOwnership',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction, interview, path) => {
        const activePerson = odSurveyHelpers.getPerson({ interview, path });
        return t('household:personDrivingLicenseOwnership', {
            context: activePerson?.gender
        });
    },
    choices: choices.yesNoDontKnow,
    conditional: conditionals.ifAge16OrMoreConditional,
    validations: validations.requiredValidation
};

export const personCarsharingMember: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'carsharingMember',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction, interview, path) => {
        const activePerson = odSurveyHelpers.getPerson({ interview, path });
        return t('household:personCarsharingMember', {
            context: activePerson?.gender
        });
    },
    choices: choices.yesNoDontKnow,
    conditional: conditionals.carsharingConditional,
    validations: validations.requiredValidation
};

export const personBikesharingUsage: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'bikesharingUsage',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('household:personBikesharingUsage'),
    choices: choices.yesNoDontKnow,
    conditional: conditionals.bikesharingConditional,
    validations: validations.requiredValidation
};

// Note: personBikesharingMembership widget is not active. This widget will not be displayed in the survey.

export const personUsedTransitInLast30Days: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'usedTransitInLast30Days',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('household:personUsedTransitInLast30Days'),
    choices: choices.yesNoDontKnow,
    conditional: conditionals.ifAge5orMoreConditional,
    validations: validations.requiredValidation
};

export const personTransitPass: WidgetConfig.InputCheckboxType = {
    ...defaultInputBase.inputCheckboxBase,
    path: 'transitPass',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('household:personTransitPass'),
    choices: choices.transitPassType,
    conditional: conditionals.transitPassConditional,
    validations: validations.requiredValidation
};

// personTransitFare : transitFareValidation · Issue #10 · chairemobilite/od_mtl
export const personTransitFare: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'transitFare',
    twoColumns: false,
    containsHtml: true,
    customPath: 'transitFareSpecify',
    customChoice: 'other',
    label: (t: TFunction) => t('household:personTransitFare'),
    helpPopup: customHelpPopup.transitFareHelpPopup,
    choices: choices.transitFareType,
    conditional: conditionals.transitFareConditional,
    validations: validations.requiredValidation
};

export const personTransitFareWarning: WidgetConfig.InputCheckboxType = {
    ...defaultInputBase.inputCheckboxBase,
    path: 'transitFareWarning',
    twoColumns: false,
    containsHtml: true,
    label: customLabels.personTransitFareWarningCustomLabel,
    choices: choices.transitFareWarning,
    conditional: customConditionals.transitFareWarningCustomConditional,
    validations: validations.optionalValidation
};

export const personHasDisability: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'hasDisability',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction, interview, path) => {
        const activePerson = odSurveyHelpers.getPerson({ interview, path });
        const nickname = _escape(activePerson?.nickname || t('survey:noNickname'));
        const countPersons = odSurveyHelpers.countPersons({ interview });
        return t('household:personHasDisability', {
            nickname,
            count: countPersons
        });
    },
    choices: choices.yesNoPreferNotToAnswer,
    conditional: customConditionals.hasOnePersonWithDisabilityOrHhSize1CustomConditional,
    validations: validations.requiredValidation
};

export const personDisabilities: WidgetConfig.InputCheckboxType = {
    ...defaultInputBase.inputCheckboxBase,
    path: 'disabilities',
    twoColumns: false,
    containsHtml: true,
    joinWith: 'personDisabilitiesSpecify',
    label: (t: TFunction) => t('household:personDisabilities'),
    choices: choices.disabilities,
    conditional: conditionals.hasDisabilityConditional,
    validations: validations.optionalValidation
};

// Exists because checkbox does not handle specify the same way as radio buttons
export const personDisabilitiesSpecify: WidgetConfig.InputStringType = {
    ...defaultInputBase.inputStringBase,
    path: 'disabilitiesSpecify',
    twoColumns: false,
    containsHtml: false,
    label: (t: TFunction) => t('household:personDisabilitiesSpecify'),
    conditional: conditionals.personDisabilityIsOtherConditional,
    validations: validations.optionalValidation
};

export const personMobilityAssistiveDevices: WidgetConfig.InputCheckboxType = {
    ...defaultInputBase.inputCheckboxBase,
    path: 'mobilityAssistiveDevices',
    twoColumns: false,
    containsHtml: true,
    joinWith: 'personMobilityAssistiveDevicesSpecify',
    label: (t: TFunction, interview, path) => {
        const activePerson = odSurveyHelpers.getPerson({ interview, path });
        const nickname = _escape(activePerson?.nickname || t('survey:noNickname'));
        const countPersons = odSurveyHelpers.countPersons({ interview });
        return t('household:personMobilityAssistiveDevices', {
            nickname,
            count: countPersons
        });
    },
    choices: choices.mobilityAssistiveDevices,
    conditional: conditionals.hasDisabilityConditional,
    validations: validations.optionalValidation
};

// Exists because checkbox does not handle specify the same way as radio buttons
export const personMobilityAssistiveDevicesSpecify: WidgetConfig.InputStringType = {
    ...defaultInputBase.inputStringBase,
    path: 'mobilityAssistiveDevicesSpecify',
    twoColumns: false,
    containsHtml: false,
    label: (t: TFunction) => t('household:personMobilityAssistiveDevicesSpecify'),
    conditional: conditionals.personAssistiveDevicesIsOtherConditional,
    validations: validations.optionalValidation
};

// personMostUsedMobilityAssistiveDevice : mostMobilityAssistiveDeviceCustomConditional · Issue #42 · chairemobilite/od_mtl
// personMostUsedMobilityAssistiveDevice : mostMobilityAssistiveDeviceCustomChoices · Issue #48 · chairemobilite/od_mtl
export const personMostUsedMobilityAssistiveDevice: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'mostUsedMobilityAssistiveDevice',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('household:personMostUsedMobilityAssistiveDevice'),
    choices: customChoices.mostUsedMobilityAssistiveDeviceCustomChoices,
    conditional: customConditionals.mostUsedMobilityAssistiveDeviceCustomConditional,
    validations: validations.optionalValidation
};

export const personUseParatransit: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'useParatransit',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction, interview, path) => {
        const activePerson = odSurveyHelpers.getPerson({ interview, path });
        const nickname = _escape(activePerson?.nickname || t('survey:noNickname'));
        const countPersons = odSurveyHelpers.countPersons({ interview });
        return t('household:personUseParatransit', {
            nickname,
            count: countPersons,
            context: activePerson?.gender
        });
    },
    choices: choices.yesNoPreferNotToAnswer,
    conditional: conditionals.hasDisabilityConditional,
    validations: validations.optionalValidation
};

export const personDisabilitiesFrequenciesParatransit: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'disabilitiesFrequenciesParatransit',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction, interview, path) => {
        const activePerson = odSurveyHelpers.getPerson({ interview, path });
        const nickname = _escape(activePerson?.nickname || t('survey:noNickname'));
        const countPersons = odSurveyHelpers.countPersons({ interview });
        return t('household:personDisabilitiesFrequenciesParatransit', {
            nickname,
            count: countPersons,
            context: activePerson?.gender
        });
    },
    choices: choices.paratransitFrequencies,
    conditional: conditionals.paratransitFrequenciesConditional,
    validations: validations.optionalValidation
};

export const personDisabilitiesFrequenciesTransit: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'disabilitiesFrequenciesTransit',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction, interview, path) => {
        const activePerson = odSurveyHelpers.getPerson({ interview, path });
        const nickname = _escape(activePerson?.nickname || t('survey:noNickname'));
        const countPersons = odSurveyHelpers.countPersons({ interview });
        return t('household:personDisabilitiesFrequenciesTransit', {
            nickname,
            count: countPersons,
            context: activePerson?.gender
        });
    },
    choices: choices.paratransitFrequenciesTransit,
    conditional: conditionals.paratransitFrequenciesConditional,
    validations: validations.optionalValidation
};

export const personStudentType: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'studentType',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction, interview, path) => {
        const activePerson = odSurveyHelpers.getPerson({ interview, path });
        return t('household:personStudentType', {
            context: activePerson?.gender
        });
    },
    helpPopup: customHelpPopup.studentHelpPopup,
    choices: choices.participationStatusStudent,
    conditional: conditionals.ifAge16OrMoreConditional,
    validations: validations.requiredValidation
};

export const personWorkerType: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'workerType',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction, interview, path) => {
        const activePerson = odSurveyHelpers.getPerson({ interview, path });
        return t('household:personWorkerType', {
            context: activePerson?.gender
        });
    },
    helpPopup: customHelpPopup.workerHelpPopup,
    choices: choices.participationStatusWorker,
    conditional: conditionals.ifAge14orMoreConditional,
    validations: validations.requiredValidation
};

export const personJob: WidgetConfig.InputStringType = {
    ...defaultInputBase.inputStringBase,
    path: 'job',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction, interview, path) => {
        const activePerson = odSurveyHelpers.getPerson({ interview, path });
        const nickname = _escape(activePerson?.nickname || t('survey:noNickname'));
        const countPersons = odSurveyHelpers.countPersons({ interview });
        return t('household:personJob', {
            nickname,
            count: countPersons
        });
    },
    conditional: conditionals.isWorkerConditional,
    validations: validations.requiredValidation
};

export const personJobType: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'jobType',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction, interview, path) => {
        const activePerson = odSurveyHelpers.getPerson({ interview, path });
        const nickname = _escape(activePerson?.nickname || t('survey:noNickname'));
        const countPersons = odSurveyHelpers.countPersons({ interview });
        return t('household:personJobType', {
            nickname,
            count: countPersons
        });
    },
    choices: choices.jobTypes,
    conditional: conditionals.isWorkerConditional,
    validations: validations.requiredValidation
};

export const personWorkPlaceType: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'workPlaceType',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction, interview, path) => {
        const activePerson = odSurveyHelpers.getPerson({ interview, path });
        const nickname = _escape(activePerson?.nickname || t('survey:noNickname'));
        const countPersons = odSurveyHelpers.countPersons({ interview });
        return t('household:personWorkPlaceType', {
            nickname,
            count: countPersons
        });
    },
    choices: choices.workPlaceTypeChoices,
    conditional: conditionals.isWorkerConditional,
    validations: validations.requiredValidation
};

export const personWorkDays: WidgetConfig.InputRadioNumberType = {
    ...defaultInputBase.inputRadioNumberBase,
    path: 'workDays',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction, interview, path) => {
        const activePerson = odSurveyHelpers.getPerson({ interview, path });
        const nickname = _escape(activePerson?.nickname || t('survey:noNickname'));
        const countPersons = odSurveyHelpers.countPersons({ interview });
        return t('household:personWorkDays', {
            nickname,
            count: countPersons
        });
    },
    valueRange: {
        min: 0,
        max: 7
    },
    conditional: conditionals.personWorkDaysConditional,
    validations: validations.requiredValidation
};

// Custom because max of RadioNumber does not accept a path with ${currentPerson}
export const personTravelToWorkDays = customWidgets.personTravelToWorkDays;

// Custom conditional to set the default value depending on previous answers
export const personOccupation: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'occupation',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('household:personOccupation'),
    choices: choices.personOccupation,
    conditional: customConditionals.personOccupationCustomConditional,
    validations: validations.requiredValidation
};

export const personEducationalAttainment: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'educationalAttainment',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('household:personEducationalAttainment'),
    choices: choices.educationalAttainment,
    conditional: conditionals.educationalAttainmentConditional,
    validations: validations.requiredValidation
};

export const household_save: WidgetConfig.ButtonWidgetConfig = {
    ...defaultInputBase.buttonNextBase,
    path: 'household.save',
    confirmPopup: customHelpPopup.validateHouseholdAgesHelpPopup,
    label: (t: TFunction) => t('household:household_save'),
    conditional: defaultConditional
};
