// This file was automatically generated by the Evolution Generator.
// The Evolution Generator is used to automate the creation of consistent, reliable code.
// Any changes made to this file will be overwritten.

import { TFunction } from 'i18next';
import _escape from 'lodash/escape';
import * as defaultInputBase from 'evolution-frontend/lib/components/inputs/defaultInputBase';
import { defaultConditional } from 'evolution-common/lib/services/widgets/conditionals/defaultConditional';
import * as WidgetConfig from 'evolution-common/lib/services/questionnaire/types';
import * as validations from 'evolution-common/lib/services/widgets/validations/validations';
import * as odSurveyHelpers from 'evolution-common/lib/services/odSurvey/helpers';
import * as choices from '../../common/choices';
import * as customLabels from '../../common/customLabels';

export const attitudinalIntro: WidgetConfig.TextWidgetConfig = {
    ...defaultInputBase.infoTextBase,
    path: 'freqAttitudinal.attitudinalIntro',
    containsHtml: true,
    text: customLabels.attitudinalIntroCustomLabel,
    conditional: defaultConditional
};

export const attitudinalOpinion: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'freqAttitudinal.attitudinalOpinion',
    twoColumns: false,
    containsHtml: true,
    label: customLabels.attitudinalOpinionCustomLabel,
    choices: choices.attitudinalChoices,
    conditional: defaultConditional,
    validations: validations.optionalValidation
};

export const attitudinalCar: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'freqAttitudinal.attitudinalCar',
    twoColumns: false,
    containsHtml: true,
    label: customLabels.attitudinalCarCustomLabel,
    choices: choices.attitudinalChoices,
    conditional: defaultConditional,
    validations: validations.optionalValidation
};

export const attitudinalTransitGoodQuality: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'freqAttitudinal.attitudinalTransitGoodQuality',
    twoColumns: false,
    containsHtml: true,
    label: customLabels.attitudinalTransitGoodQualityCustomLabel,
    choices: choices.attitudinalChoices,
    conditional: defaultConditional,
    validations: validations.optionalValidation
};

export const attitudinalFamiliarWithTransit: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'freqAttitudinal.attitudinalFamiliarWithTransit',
    twoColumns: false,
    containsHtml: true,
    label: customLabels.attitudinalFamiliarWithTransitCustomLabel,
    choices: choices.attitudinalChoices,
    conditional: defaultConditional,
    validations: validations.optionalValidation
};

export const attitudinalRequireHighLevel: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'freqAttitudinal.attitudinalRequireHighLevel',
    twoColumns: false,
    containsHtml: true,
    label: customLabels.attitudinalRequireHighLevelCustomLabel,
    choices: choices.attitudinalChoices,
    conditional: defaultConditional,
    validations: validations.optionalValidation
};

export const attitudinalEasyWithoutCar: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'freqAttitudinal.attitudinalEasyWithoutCar',
    twoColumns: false,
    containsHtml: true,
    label: customLabels.attitudinalEasyWithoutCarCustomLabel,
    choices: choices.attitudinalChoices,
    conditional: defaultConditional,
    validations: validations.optionalValidation
};

export const attitudinalGoodAccessImportant: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'freqAttitudinal.attitudinalGoodAccessImportant',
    twoColumns: false,
    containsHtml: true,
    label: customLabels.attitudinalGoodAccessImportantCustomLabel,
    choices: choices.attitudinalChoices,
    conditional: defaultConditional,
    validations: validations.optionalValidation
};

export const buttonCompleteAttitudinalSection: WidgetConfig.ButtonWidgetConfig = {
    ...defaultInputBase.buttonNextBase,
    path: 'buttonCompleteAttitudinalSection',
    label: (t: TFunction) => t('attitudinal:buttonCompleteAttitudinalSection'),
    conditional: defaultConditional
};
