// This file was automatically generated by the Evolution Generator.
// The Evolution Generator is used to automate the creation of consistent, reliable code.
// Any changes made to this file will be overwritten.

import { TFunction } from 'i18next';
import * as defaultInputBase from 'evolution-frontend/lib/components/inputs/defaultInputBase';
import { defaultConditional } from 'evolution-common/lib/services/widgets/conditionals/defaultConditional';
import * as WidgetConfig from 'evolution-common/lib/services/questionnaire/types';
import * as validations from 'evolution-common/lib/services/widgets/validations/validations';
import * as choices from '../../common/choices';

export const attitudinalIntro: WidgetConfig.TextWidgetConfig = {
    ...defaultInputBase.infoTextBase,
    path: 'freqAttitudinal.attitudinalIntro',
    containsHtml: true,
    text: (t: TFunction) => t('attitudinal:attitudinalIntro'),
    conditional: defaultConditional
};

export const attitudinalOpinion: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'freqAttitudinal.attitudinalOpinion',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('attitudinal:attitudinalOpinion'),
    choices: choices.attitudinalChoices,
    conditional: defaultConditional,
    validations: validations.optionalValidation
};

export const attitudinalCar: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'freqAttitudinal.attitudinalCar',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('attitudinal:attitudinalCar'),
    choices: choices.attitudinalChoices,
    conditional: defaultConditional,
    validations: validations.optionalValidation
};

export const attitudinalTransitGoodQuality: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'freqAttitudinal.attitudinalTransitGoodQuality',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('attitudinal:attitudinalTransitGoodQuality'),
    choices: choices.attitudinalChoices,
    conditional: defaultConditional,
    validations: validations.optionalValidation
};

export const attitudinalFamiliarWithTransit: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'freqAttitudinal.attitudinalFamiliarWithTransit',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('attitudinal:attitudinalFamiliarWithTransit'),
    choices: choices.attitudinalChoices,
    conditional: defaultConditional,
    validations: validations.optionalValidation
};

export const attitudinalRequireHighLevel: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'freqAttitudinal.attitudinalRequireHighLevel',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('attitudinal:attitudinalRequireHighLevel'),
    choices: choices.attitudinalChoices,
    conditional: defaultConditional,
    validations: validations.optionalValidation
};

export const attitudinalEasyWithoutCar: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'freqAttitudinal.attitudinalEasyWithoutCar',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('attitudinal:attitudinalEasyWithoutCar'),
    choices: choices.attitudinalChoices,
    conditional: defaultConditional,
    validations: validations.optionalValidation
};

export const attitudinalGoodAccessImportant: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'freqAttitudinal.attitudinalGoodAccessImportant',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('attitudinal:attitudinalGoodAccessImportant'),
    choices: choices.attitudinalChoices,
    conditional: defaultConditional,
    validations: validations.optionalValidation
};

export const buttonCompleteAttitudinalSection: WidgetConfig.ButtonWidgetConfig = {
    ...defaultInputBase.buttonNextBase,
    path: 'buttonCompleteAttitudinalSection',
    label: (t: TFunction) => t('attitudinal:buttonCompleteAttitudinalSection'),
    conditional: defaultConditional
};
