// This file was automatically generated by the Evolution Generator.
// The Evolution Generator is used to automate the creation of consistent, reliable code.
// Any changes made to this file will be overwritten.

import { TFunction } from 'i18next';
import * as defaultInputBase from 'evolution-frontend/lib/components/inputs/defaultInputBase';
import { defaultConditional } from 'evolution-common/lib/services/widgets/conditionals/defaultConditional';
import * as WidgetConfig from 'evolution-common/lib/services/questionnaire/types';
import * as validations from 'evolution-common/lib/services/widgets/validations/validations';
import * as conditionals from '../../common/conditionals';
import * as customWidgets from './customWidgets';

export const completedTextOutOfTerritory: WidgetConfig.TextWidgetConfig = {
    ...defaultInputBase.infoTextBase,
    path: 'completedTextOutOfTerritory',
    containsHtml: true,
    text: (t: TFunction) => t('completed:completedTextOutOfTerritory'),
    conditional: conditionals.homeNotInTerritoryConditional
};

export const completedText: WidgetConfig.TextWidgetConfig = {
    ...defaultInputBase.infoTextBase,
    path: 'completedText',
    containsHtml: true,
    text: (t: TFunction) => t('completed:completedText'),
    conditional: conditionals.homeInTerritoryConditional
};

export const buttonARTMPanel = customWidgets.buttonARTMPanel;

// Note: mapARTMImage widget is not active. This widget will not be displayed in the survey.
