// This file was automatically generated by the Evolution Generator.
// The Evolution Generator is used to automate the creation of consistent, reliable code.
// Any changes made to this file will be overwritten.

import { TFunction } from 'i18next';
import * as defaultInputBase from 'evolution-frontend/lib/components/inputs/defaultInputBase';
import { defaultConditional } from 'evolution-common/lib/services/widgets/conditionals/defaultConditional';
import * as WidgetConfig from 'evolution-common/lib/services/questionnaire/types';
import * as validations from 'evolution-common/lib/services/widgets/validations/validations';
import * as surveyHelper from 'evolution-common/lib/utils/helpers';
import * as choices from '../../common/choices';
import * as conditionals from '../../common/conditionals';
import * as formatters from 'evolution-common/lib/utils/formatters';
import * as customConditionals from '../../common/customConditionals';
import * as customWidgets from './customWidgets';
import * as customHelpPopup from '../../common/customHelpPopup';
import * as customValidations from '../../common/customValidations';
import * as customLabels from '../../common/customLabels';

export const acceptToBeContactedForHelp: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'acceptToBeContactedForHelp',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('home:acceptToBeContactedForHelp'),
    choices: choices.yesNo,
    conditional: defaultConditional,
    validations: validations.requiredValidation
};

export const wantToParticipateToDraw: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'wantToParticipateToDraw',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('home:wantToParticipateToDraw'),
    choices: choices.yesNo,
    conditional: defaultConditional,
    validations: validations.requiredValidation
};

export const contactInformationIntro: WidgetConfig.TextWidgetConfig = {
    ...defaultInputBase.infoTextBase,
    path: 'contactInformationIntro',
    containsHtml: true,
    text: (t: TFunction) => t('home:contactInformationIntro'),
    conditional: conditionals.acceptsToBeContactedForHelp
};

export const contactEmail: WidgetConfig.InputStringType = {
    ...defaultInputBase.inputStringBase,
    path: 'contactEmail',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('home:contactEmail'),
    conditional: conditionals.acceptsToBeContactedForHelp,
    validations: validations.emailValidation
};

export const homeIntro: WidgetConfig.TextWidgetConfig = {
    ...defaultInputBase.infoTextBase,
    path: 'homeIntro',
    containsHtml: true,
    text: (t: TFunction) => t('home:homeIntro'),
    conditional: conditionals.homeAddressIsPrefilledConditional
};

export const homeAddress: WidgetConfig.InputStringType = {
    ...defaultInputBase.inputStringBase,
    path: 'home.address',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('home:homeAddress'),
    conditional: defaultConditional,
    validations: validations.requiredValidation
};

export const homeCity: WidgetConfig.InputStringType = {
    ...defaultInputBase.inputStringBase,
    path: 'home.city',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('home:homeCity'),
    conditional: defaultConditional,
    validations: validations.requiredValidation
};

export const homePostalCode: WidgetConfig.InputStringType = {
    ...defaultInputBase.inputStringBase,
    path: 'home.postalCode',
    twoColumns: false,
    containsHtml: true,
    inputFilter: formatters.canadianPostalCodeFormatter,
    label: (t: TFunction) => t('home:homePostalCode'),
    conditional: defaultConditional,
    validations: validations.postalCodeValidation
};

// FIXME home_geography : territoryValidation · Issue #8 · chairemobilite/od_mtl
export const homeGeography = customWidgets.homeGeography;

// Si réponse est non, terminer enquête (action à ajouter sur le serveur)
// Custom label pour ajouter l'adresse au libellé
export const homeIsMain: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'home.isMain',
    twoColumns: false,
    containsHtml: true,
    label: customLabels.homeIsMainCustomLabel,
    choices: choices.homeIsMain,
    conditional: customConditionals.sdrWithSecondaryHousesCustomConditional,
    validations: validations.requiredValidation
};

export const householdOwnership: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'household.ownership',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('home:householdOwnership'),
    helpPopup: customHelpPopup.householdOwnershipHelpPopup,
    choices: choices.householdOwnershipChoices,
    conditional: defaultConditional,
    validations: validations.requiredValidation
};

// Custom label because of the assigned date interpolation
export const householdSize: WidgetConfig.InputRadioNumberType = {
    ...defaultInputBase.inputRadioNumberBase,
    path: 'household.size',
    twoColumns: false,
    containsHtml: true,
    label: customLabels.householdSizeCustomLabel,
    valueRange: {
        min: 1,
        max: 6
    },
    overMaxAllowed: true,
    helpPopup: customHelpPopup.householdSizeHelpPopup,
    conditional: defaultConditional,
    validations: validations.householdSizeValidation
};

export const householdCarNumber: WidgetConfig.InputRadioNumberType = {
    ...defaultInputBase.inputRadioNumberBase,
    path: 'household.carNumber',
    twoColumns: false,
    containsHtml: true,
    joinWith: 'householdTwoWheelNumber',
    label: (t: TFunction) => t('home:householdCarNumber'),
    valueRange: {
        min: 0,
        max: 4
    },
    overMaxAllowed: true,
    helpPopup: customHelpPopup.householdCarNumberHelpPopup,
    conditional: defaultConditional,
    validations: validations.carNumberValidation
};

export const householdTwoWheelNumber: WidgetConfig.InputRadioNumberType = {
    ...defaultInputBase.inputRadioNumberBase,
    path: 'household.twoWheelNumber',
    twoColumns: false,
    containsHtml: true,
    joinWith: 'householdBicycleNumber',
    label: (t: TFunction) => t('home:householdTwoWheelNumber'),
    valueRange: {
        min: 0,
        max: 4
    },
    overMaxAllowed: true,
    helpPopup: customHelpPopup.twoWheelNumberHelpPopup,
    conditional: defaultConditional,
    validations: validations.requiredValidation
};

export const householdBicycleNumber: WidgetConfig.InputRadioNumberType = {
    ...defaultInputBase.inputRadioNumberBase,
    path: 'household.bicycleNumber',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('home:householdBicycleNumber'),
    valueRange: {
        min: 0,
        max: 4
    },
    overMaxAllowed: true,
    conditional: defaultConditional,
    validations: validations.bicycleNumberValidation
};

export const householdElectricBicycleNumber: WidgetConfig.InputRadioNumberType = {
    ...defaultInputBase.inputRadioNumberBase,
    path: 'household.electricBicycleNumber',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('home:householdElectricBicycleNumber'),
    valueRange: {
        min: 0,
        max: (interview) => surveyHelper.getResponse(interview, 'household.bicycleNumber', 0) as any
    },
    conditional: conditionals.hasHouseholdBicycleConditional,
    validations: validations.bicycleNumberValidation
};

// Custom label because of the car number plural
export const homeCarParkingsAvailableVehicleHousehold: WidgetConfig.InputCheckboxType = {
    ...defaultInputBase.inputCheckboxBase,
    path: 'home.carParkingAvailableVehicleHousehold',
    twoColumns: false,
    containsHtml: true,
    label: customLabels.homeParkingAvailableCustomLabel,
    choices: choices.carParkingsHome,
    conditional: conditionals.carParkingHomeWithVehicleConditional,
    validations: validations.requiredValidation
};

export const homeCarParkingsAvailableNoVehicleHousehold: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'home.carParkingAvailableNoVehicleHousehold',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('home:homeCarParkingsAvailableNoVehicleHousehold'),
    choices: choices.yesNo,
    conditional: conditionals.carParkingHomeWithoutVehicleConditional,
    validations: validations.requiredValidation
};

export const householdCarsharing: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'household.carsharing',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('home:householdCarsharing'),
    choices: choices.yesNoDontKnow,
    conditional: conditionals.sharingMobilitiesConditional,
    validations: validations.requiredValidation
};

export const householdBikesharing: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'household.bikesharing',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('home:householdBikesharing'),
    choices: choices.yesNoDontKnow,
    conditional: conditionals.sharingMobilitiesConditional,
    validations: validations.requiredValidation
};

export const householdAtLeastOnePersonWithDisability: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'household.atLeastOnePersonWithDisability',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('home:householdAtLeastOnePersonWithDisability'),
    choices: choices.yesNoPreferNotToAnswer,
    conditional: conditionals.hasHouseholdSize2OrMoreConditional,
    validations: validations.requiredValidation
};

export const home_save: WidgetConfig.ButtonWidgetConfig = {
    ...defaultInputBase.buttonNextBase,
    path: 'home.save',
    label: (t: TFunction) => t('home:home_save'),
    conditional: defaultConditional
};
