// This file was automatically generated by the Evolution Generator.
// The Evolution Generator is used to automate the creation of consistent, reliable code.
// Any changes made to this file will be overwritten.

import { isSectionCompleted } from 'evolution-common/lib/services/questionnaire/sections/navigationHelpers';
import { SectionConfig } from 'evolution-common/lib/services/questionnaire/types';
import { widgetsNames } from './widgetsNames';
import { getPersonsOfDrivingAge, updateHouseholdSizeFromPersonCount } from '../../common/customHelpers';
import { allPersonsTripDiariesCompleted } from '../../common/helper';
import { preEndNoDisabilityConditional } from '../../common/commonHelpers';

export const currentSectionName: string = 'frequencies';
const previousSectionName: SectionConfig['previousSection'] = 'selectFreqPerson';
const nextSectionName: SectionConfig['nextSection'] = 'attitudinal';

const visibleEps = ['freqAttitudinal', 'freqBarriers', 'freqAttitudinalBarriers'];

// Config for the section
export const sectionConfig: SectionConfig = {
    previousSection: previousSectionName,
    nextSection: nextSectionName,
    title: {
        fr: 'Fréquences par mode',
        en: 'Mode frequencies'
    },
    navMenu: {
        type: 'hidden',
        parentSection: 'end'
    },
    widgets: widgetsNames,
    // Do some actions before the section is loaded
    // Allow to click on the section menu
    enableConditional: function (interview) {
        // FIXME Wrong condition but it works for now. Evolution should support blocks of optional sections See https://github.com/chairemobilite/evolution/issues/1634
        return allPersonsTripDiariesCompleted(interview);
    },
    // Determine if the current section is completed
    completionConditional: function (interview) {
        // Completed if ep is not mtmd or actually completed
        return (
            !preEndNoDisabilityConditional(interview, visibleEps) ||
            isSectionCompleted({ interview, sectionName: currentSectionName })
        );
    },
    onSectionEntry: (interview) => {
        // Set the _freqPersonId if there is only one person, otherwise, it was
        // set in another section
        const hhMembersOfDrivingLicenseAge = getPersonsOfDrivingAge(interview);
        if (hhMembersOfDrivingLicenseAge.length !== 1) {
            // The response should have been set in the selectFreqPerson
            // section, just return empty values
            return {};
        }
        return { 'response._freqPersonId': hhMembersOfDrivingLicenseAge[0]._uuid };
    },
    isSectionVisible: (interview) => {
        // Section visible seulement si ep exclusif est est l'un des 3 avec freq
        return preEndNoDisabilityConditional(interview, visibleEps);
    }
};

export default sectionConfig;
