// This file was automatically generated by the Evolution Generator.
// The Evolution Generator is used to automate the creation of consistent, reliable code.
// Any changes made to this file will be overwritten.

import { TFunction } from 'i18next';
import _escape from 'lodash/escape';
import * as defaultInputBase from 'evolution-frontend/lib/components/inputs/defaultInputBase';
import { defaultConditional } from 'evolution-common/lib/services/widgets/conditionals/defaultConditional';
import * as WidgetConfig from 'evolution-common/lib/services/questionnaire/types';
import * as validations from 'evolution-common/lib/services/widgets/validations/validations';
import * as odSurveyHelpers from 'evolution-common/lib/services/odSurvey/helpers';
import * as choices from '../../common/choices';
import * as conditionals from '../../common/conditionals';
import * as customLabels from '../../common/customLabels';

export const anyTripModeFrequenciesIntro: WidgetConfig.TextWidgetConfig = {
    ...defaultInputBase.infoTextBase,
    path: 'freqAttitudinal.anyTripModeFrequenciesIntro',
    containsHtml: true,
    text: customLabels.frequencyIntroCustomLabel,
    conditional: defaultConditional
};

export const anyTripModeFrequenciesWalk: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'freqAttitudinal.anyTripModeFrequenciesWalk',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('frequencies:anyTripModeFrequenciesWalk'),
    choices: choices.anyTripModeFrequenciesChoices,
    conditional: defaultConditional,
    validations: validations.optionalValidation
};

export const anyTripModeFrequenciesBicycle: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'freqAttitudinal.anyTripModeFrequenciesBicycle',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('frequencies:anyTripModeFrequenciesBicycle'),
    choices: choices.anyTripModeFrequenciesChoices,
    conditional: defaultConditional,
    validations: validations.optionalValidation
};

export const anyTripModeFrequenciesTransit: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'freqAttitudinal.anyTripModeFrequenciesTransit',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('frequencies:anyTripModeFrequenciesTransit'),
    choices: choices.anyTripModeFrequenciesChoices,
    conditional: defaultConditional,
    validations: validations.optionalValidation
};

export const anyTripModeFrequenciesCarPassenger: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'freqAttitudinal.anyTripModeFrequenciesCarPassenger',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('frequencies:anyTripModeFrequenciesCarPassenger'),
    choices: choices.anyTripModeFrequenciesChoices,
    conditional: defaultConditional,
    validations: validations.optionalValidation
};

export const anyTripModeFrequenciesCarDriver: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'freqAttitudinal.anyTripModeFrequenciesCarDriver',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('frequencies:anyTripModeFrequenciesCarDriver'),
    choices: choices.anyTripModeFrequenciesChoices,
    conditional: conditionals.hasDrivingLicenseConditional,
    validations: validations.optionalValidation
};

export const buttonCompleteFrequenciesSection: WidgetConfig.ButtonWidgetConfig = {
    ...defaultInputBase.buttonNextBase,
    path: 'buttonCompleteFrequenciesSection',
    label: (t: TFunction) => t('frequencies:buttonCompleteFrequenciesSection'),
    conditional: defaultConditional
};
