// This file was automatically generated by the Evolution Generator.
// The Evolution Generator is used to automate the creation of consistent, reliable code.
// Any changes made to this file will be overwritten.

import moment from 'moment';
import { isSectionCompleted } from 'evolution-common/lib/services/questionnaire/sections/navigationHelpers';
import { SectionConfig } from 'evolution-common/lib/services/questionnaire/types';
import { widgetsNames } from './widgetsNames';
import { getResponse } from 'evolution-common/lib/utils/helpers';

export const currentSectionName: string = 'accessCode';
const previousSectionName: SectionConfig['previousSection'] = null;
const nextSectionName: SectionConfig['nextSection'] = 'home';
const parentSection = 'home';

// Config for the section
export const sectionConfig: SectionConfig = {
    previousSection: previousSectionName,
    nextSection: nextSectionName,
    title: {
        fr: 'Code d\'accès',
        en: 'Access code'
    },
    navMenu: {
        type: 'hidden',
        parentSection: parentSection
    },
    widgets: widgetsNames,
    // Allow to click on the section menu
    enableConditional: true,
    // Determine if the current section is completed
    completionConditional: function (interview) {
        return isSectionCompleted({ interview, sectionName: currentSectionName });
    },
    isSectionVisible: (interview) => {
        // We should not go back to this section once the access code is confirmed
        const accessCodeConfirmed = getResponse(interview, '_accessCodeConfirmed');
        return accessCodeConfirmed !== true;
    },
    onSectionEntry: function (interview, _iterationContext) {
        // Set the previous day if not set yet
        const previousDay = getResponse(interview, '_previousDay');
        if (!previousDay) {
            return { 'response._previousDay': moment().subtract(1, 'days').format('YYYY-MM-DD') };
        }
        return undefined;
    }
};

export default sectionConfig;
