// This file was automatically generated by the Evolution Generator.
// The Evolution Generator is used to automate the creation of consistent, reliable code.
// Any changes made to this file will be overwritten.

import { TFunction } from 'i18next';
import * as defaultInputBase from 'evolution-frontend/lib/components/inputs/defaultInputBase';
import { defaultConditional } from 'evolution-common/lib/services/widgets/conditionals/defaultConditional';
import * as WidgetConfig from 'evolution-common/lib/services/questionnaire/types';
import * as validations from 'evolution-common/lib/services/widgets/validations/validations';
import * as choices from '../../common/choices';
import * as conditionals from '../../common/conditionals';
import * as formatters from 'evolution-common/lib/utils/formatters';
import * as customWidgets from './customWidgets';
import * as customValidations from '../../common/customValidations';

// Cacher la question lorsque le code a été validé et pré-rempli pour empêcher de pouvoir venir le modifier
export const accessCode: WidgetConfig.InputStringType = {
    ...defaultInputBase.inputStringBase,
    path: 'accessCode',
    twoColumns: false,
    containsHtml: true,
    inputFilter: formatters.accessCodeFormatter,
    label: (t: TFunction) => t('accessCode:accessCode'),
    conditional: conditionals.isAccessCodeNotValidConditional,
    validations: validations.accessCodeValidation
};

export const accessCodeIsCorrectConfirmation: WidgetConfig.InputCheckboxType = {
    ...defaultInputBase.inputCheckboxBase,
    path: 'accessCodeIsCorrect',
    twoColumns: false,
    containsHtml: false,
    label: (t: TFunction) => t('accessCode:accessCodeIsCorrectConfirmation'),
    choices: choices.accessCodeConfirmChoices,
    conditional: conditionals.isAccessCodeInvalidConditional,
    validations: customValidations.accessCodeConfirmIsCheckedCustomValidation
};

// Custom car le bouton doit envoyer un champ pour informer le backend de pré-remplir les champs ou retourner invalide.
export const accessCode_confirm = customWidgets.accessCode_confirm;
