// This file was automatically generated by the Evolution Generator.
// The Evolution Generator is used to automate the creation of consistent, reliable code.
// Any changes made to this file will be overwritten.

import { isSectionCompleted } from 'evolution-common/lib/services/questionnaire/sections/navigationHelpers';
import { SectionConfig } from 'evolution-common/lib/services/questionnaire/types';
import { widgetsNames } from './widgetsNames';
import { updateHouseholdSizeFromPersonCount } from '../../common/customHelpers';
import { getResponse } from 'evolution-common/lib/utils/helpers';
import { allPersonsTripDiariesCompleted } from '../../common/helper';

export const currentSectionName: string = 'end';
const previousSectionName: SectionConfig['previousSection'] = 'longDistance';
const nextSectionName: SectionConfig['nextSection'] = 'completed';

// Config for the section
export const sectionConfig: SectionConfig = {
    previousSection: previousSectionName,
    nextSection: nextSectionName,
    title: {
        fr: 'Fin',
        en: 'End'
    },
    navMenu: {
        type: 'hidden',
        parentSection: previousSectionName
    },
    widgets: widgetsNames,
    // Allow to click on the section menu
    enableConditional: function (interview) {
        // Conditional depends on the partial sample, some have sections between
        // tripDiary and end, others don't, in which case we wait for all trip
        // diaries to be completed.
        const exclusiveEP = getResponse(interview, 'ep.exclusive');
        // FIXME add other previous sections as they are implemented
        const actualPreviousSection = exclusiveEP === 'mtmd' ? 'longDistance' : undefined;
        if (actualPreviousSection === undefined) {
            return allPersonsTripDiariesCompleted(interview);
        }
        return isSectionCompleted({ interview, sectionName: actualPreviousSection });
    },
    // Allow to click on the section menu
    completionConditional: function (interview) {
        return isSectionCompleted({ interview, sectionName: currentSectionName });
    },
    onSectionEntry: updateHouseholdSizeFromPersonCount
};

export default sectionConfig;
