// This file was automatically generated by the Evolution Generator.
// The Evolution Generator is used to automate the creation of consistent, reliable code.
// Any changes made to this file will be overwritten.

import { TFunction } from 'i18next';
import * as defaultInputBase from 'evolution-frontend/lib/components/inputs/defaultInputBase';
import { defaultConditional } from 'evolution-common/lib/services/widgets/conditionals/defaultConditional';
import * as WidgetConfig from 'evolution-common/lib/services/questionnaire/types';
import * as validations from 'evolution-common/lib/services/widgets/validations/validations';
import * as choices from '../../common/choices';
import * as conditionals from '../../common/conditionals';
import * as inputRange from '../../common/inputRange';
import * as customChoices from './customChoices';
import * as customHelpPopup from '../../common/customHelpPopup';
import * as customValidations from '../../common/customValidations';
import * as customLabels from '../../common/customLabels';

export const householdType: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'household.type',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('end:householdType'),
    choices: choices.householdType,
    conditional: conditionals.householdTypeConditional,
    validations: validations.optionalValidation
};

// Note: householdTypeSpecify widget is not active. This widget will not be displayed in the survey.

export const householdPluginHybridCarNumber: WidgetConfig.InputRadioNumberType = {
    ...defaultInputBase.inputRadioNumberBase,
    path: 'household.pluginHybridCarNumber',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('end:householdPluginHybridCarNumber'),
    valueRange: {
        min: 0,
        max: 4
    },
    overMaxAllowed: true,
    conditional: conditionals.householdHasCars,
    validations: customValidations.householdHybridCarCountCustomValidation
};

export const householdElectricCarNumber: WidgetConfig.InputRadioNumberType = {
    ...defaultInputBase.inputRadioNumberBase,
    path: 'household.electricCarNumber',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('end:householdElectricCarNumber'),
    valueRange: {
        min: 0,
        max: 4
    },
    overMaxAllowed: true,
    conditional: conditionals.householdHasCars,
    validations: customValidations.householdElectricCarCountCustomValidation
};

export const householdIncome: WidgetConfig.InputSelectType = {
    ...defaultInputBase.inputSelectBase,
    path: 'household.income',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('end:householdIncome'),
    helpPopup: customHelpPopup.incomeHelpPopup,
    choices: choices.householdIncomeChoices,
    conditional: defaultConditional,
    validations: validations.optionalValidation
};

export const didRespondForCorrectAssignedDate: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'end.didRespondForCorrectAssignedDate',
    twoColumns: false,
    containsHtml: true,
    label: customLabels.didRespondForCorrectDateCustomLabel,
    choices: customChoices.didRespondForCorrectAssignedDateCustomChoices,
    conditional: conditionals.didRespondForCorrectAssignedDateConditional,
    validations: validations.optionalValidation
};

export const didNotRespondForCorrectAssignedDateReasons: WidgetConfig.InputCheckboxType = {
    ...defaultInputBase.inputCheckboxBase,
    path: 'end.didNotRespondForCorrectAssignedDateReasons',
    twoColumns: false,
    containsHtml: true,
    label: customLabels.didNotRespondForCorrectDateReasonCustomLabel,
    choices: choices.didNotRespondForCorrectAssignedDateReasons,
    conditional: conditionals.didNotRespondForCorrectAssignedDateConditional,
    validations: validations.optionalValidation
};

export const wouldLikeToParticipateInOtherSurveysChaireMobilite: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'end.wouldLikeToParticipateInOtherSurveysChaireMobilite',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('end:wouldLikeToParticipateInOtherSurveysChaireMobilite'),
    choices: choices.yesNo,
    conditional: defaultConditional,
    validations: validations.optionalValidation
};

export const wouldLikeToParticipateInOtherSurveysChaireMobiliteContactEmail: WidgetConfig.InputStringType = {
    ...defaultInputBase.inputStringBase,
    path: 'end.wouldLikeToParticipateInOtherSurveysChaireMobiliteContactEmail',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('end:wouldLikeToParticipateInOtherSurveysChaireMobiliteContactEmail'),
    conditional: conditionals.wantToParticipateInOtherSurveysChaireMobiliteConditional,
    validations: validations.emailValidation
};

export const householdCommentsOnSurvey: WidgetConfig.InputTextType = {
    ...defaultInputBase.textBase,
    path: 'end.commentsOnSurvey',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('end:householdCommentsOnSurvey'),
    conditional: defaultConditional,
    validations: validations.optionalValidation
};

export const optionalIntroText: WidgetConfig.TextWidgetConfig = {
    ...defaultInputBase.infoTextBase,
    path: 'end.optionalIntroText',
    containsHtml: true,
    text: (t: TFunction) => t('end:optionalIntroText'),
    conditional: conditionals.enmpConditional
};

export const endInterestOfTheSurvey: WidgetConfig.InputRangeType = {
    ...defaultInputBase.inputRangeBase,
    ...inputRange.sliderNotAtAllToVeryInteresting,
    path: 'end.interestOfTheSurvey',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('end:endInterestOfTheSurvey'),
    conditional: conditionals.enmpConditional,
    validations: customValidations.rangeOptionalOrValidCustomValidation
};

export const endTimeSpentAnswering: WidgetConfig.InputStringType = {
    ...defaultInputBase.inputNumberBase,
    path: 'end.timeSpentAnswering',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('end:endTimeSpentAnswering'),
    conditional: conditionals.enmpConditional,
    validations: validations.optionalValidation
};

export const endDurationOfTheSurvey: WidgetConfig.InputRangeType = {
    ...defaultInputBase.inputRangeBase,
    ...inputRange.sliderTooShortToTooLong,
    path: 'end.durationOfTheSurvey',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('end:endDurationOfTheSurvey'),
    conditional: conditionals.enmpConditional,
    validations: customValidations.rangeOptionalOrValidCustomValidation
};

export const endDifficultyOfTheSurvey: WidgetConfig.InputRangeType = {
    ...defaultInputBase.inputRangeBase,
    ...inputRange.sliderVeryEasyToVeryDifficult,
    path: 'end.difficultyOfTheSurvey',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('end:endDifficultyOfTheSurvey'),
    conditional: conditionals.enmpConditional,
    validations: customValidations.rangeOptionalOrValidCustomValidation
};

export const endBurdenOfTheSurvey: WidgetConfig.InputRangeType = {
    ...defaultInputBase.inputRangeBase,
    ...inputRange.sliderNotAtAllToVeryBurdensome,
    path: 'end.burdenOfTheSurvey',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('end:endBurdenOfTheSurvey'),
    conditional: conditionals.enmpConditional,
    validations: customValidations.rangeOptionalOrValidCustomValidation
};

export const endConsideredAbandoningSurvey: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'end.consideredAbandoningSurvey',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('end:endConsideredAbandoningSurvey'),
    choices: choices.yesNoDontKnow,
    conditional: conditionals.enmpConditional,
    validations: validations.optionalValidation
};

export const buttonCompleteInterviewWithCompleteSection: WidgetConfig.ButtonWidgetConfig = {
    ...defaultInputBase.buttonNextBase,
    path: 'buttonCompleteInterviewWithCompleteSection',
    label: (t: TFunction) => t('end:buttonCompleteInterviewWithCompleteSection'),
    conditional: defaultConditional
};
