// This file was automatically generated by the Evolution Generator.
// The Evolution Generator is used to automate the creation of consistent, reliable code.
// Any changes made to this file will be overwritten.

import { isSectionCompleted } from 'evolution-common/lib/services/questionnaire/sections/navigationHelpers';
import { SectionConfig } from 'evolution-common/lib/services/questionnaire/types';
import { widgetsNames } from './widgetsNames';
import { getBarriersDisabilityTripPath, getBarriersTripPath } from '../../common/customHelpers';
import { allPersonsTripDiariesCompleted } from '../../common/helper';
import { preEndNoDisabilityConditional } from '../../common/commonHelpers';

export const currentSectionName: string = 'barriers';
const previousSectionName: SectionConfig['previousSection'] = 'attitudinal';
const nextSectionName: SectionConfig['nextSection'] = 'end';

const visibleEps = ['freqBarriers', 'freqAttitudinalBarriers'];

// Config for the section
export const sectionConfig: SectionConfig = {
    previousSection: previousSectionName,
    nextSection: nextSectionName,
    title: {
        fr: 'Freins au TC',
        en: 'Barriers to transit'
    },
    navMenu: {
        type: 'hidden',
        parentSection: 'end'
    },
    widgets: widgetsNames,
    // Do some actions before the section is loaded
    // Allow to click on the section menu
    enableConditional: function (interview) {
        // FIXME Wrong condition but it works for now. Evolution should support blocks of optional sections See https://github.com/chairemobilite/evolution/issues/1634
        return allPersonsTripDiariesCompleted(interview);
    },
    // Determine if the current section is completed
    completionConditional: function (interview) {
        // Completed if ep is not mtmd or actually completed
        return (
            !preEndNoDisabilityConditional(interview, visibleEps) ||
            isSectionCompleted({ interview, sectionName: currentSectionName })
        );
    },
    onSectionEntry: (interview) => {
        const barrierTripPath = getBarriersTripPath(interview);
        const barrierDisabilityTripPath = getBarriersDisabilityTripPath(interview);
        return {
            'response._barriersTripPath': barrierTripPath,
            'response._barriersDisabilityTripPath': barrierDisabilityTripPath
        };
    },
    isSectionVisible: (interview) => {
        // Section visible seulement si ep exclusif est est l'un des 3 avec freq
        if (!preEndNoDisabilityConditional(interview, visibleEps)) {
            return false;
        }
        const barrierTripPath = getBarriersTripPath(interview);
        const barrierDisabilityTripPath = getBarriersDisabilityTripPath(interview);
        return barrierTripPath !== null || barrierDisabilityTripPath !== null;
    }
};

export default sectionConfig;
