// This file was automatically generated by the Evolution Generator.
// The Evolution Generator is used to automate the creation of consistent, reliable code.
// Any changes made to this file will be overwritten.

import { TFunction } from 'i18next';
import * as defaultInputBase from 'evolution-frontend/lib/components/inputs/defaultInputBase';
import { defaultConditional } from 'evolution-common/lib/services/widgets/conditionals/defaultConditional';
import * as WidgetConfig from 'evolution-common/lib/services/questionnaire/types';
import * as validations from 'evolution-common/lib/services/widgets/validations/validations';
import * as choices from '../../common/choices';
import * as conditionals from '../../common/conditionals';
import * as customLabels from '../../common/customLabels';

export const barriersTrip: WidgetConfig.TextWidgetConfig = {
    ...defaultInputBase.infoTextBase,
    path: 'barriersTrip',
    containsHtml: true,
    text: customLabels.barriersTripCustomLabel,
    conditional: conditionals.hasBarrierTripConditional
};

export const barriersIntro: WidgetConfig.TextWidgetConfig = {
    ...defaultInputBase.infoTextBase,
    path: 'barriersIntro',
    containsHtml: true,
    text: (t: TFunction) => t('barriers:barriersIntro'),
    conditional: conditionals.hasBarrierTripConditional
};

export const barriersFrequency: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'barriersFrequency',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('barriers:barriersFrequency'),
    choices: choices.barriersChoices,
    conditional: conditionals.hasBarrierTripConditional,
    validations: validations.optionalValidation
};

export const barriersReliability: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'barriersReliability',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('barriers:barriersReliability'),
    choices: choices.barriersChoices,
    conditional: conditionals.hasBarrierTripConditional,
    validations: validations.optionalValidation
};

export const barriersWalk: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'barriersWalk',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('barriers:barriersWalk'),
    choices: choices.barriersChoices,
    conditional: conditionals.hasBarrierTripConditional,
    validations: validations.optionalValidation
};

export const barriersTime: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'barriersTime',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('barriers:barriersTime'),
    choices: choices.barriersChoices,
    conditional: conditionals.hasBarrierTripConditional,
    validations: validations.optionalValidation
};

export const barriersTransfer: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'barriersTransfer',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('barriers:barriersTransfer'),
    choices: choices.barriersChoices,
    conditional: conditionals.hasBarrierTripConditional,
    validations: validations.optionalValidation
};

export const barriersSecurity: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'barriersSecurity',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('barriers:barriersSecurity'),
    choices: choices.barriersChoices,
    conditional: conditionals.hasBarrierTripConditional,
    validations: validations.optionalValidation
};

export const barriersPlanning: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'barriersPlanning',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('barriers:barriersPlanning'),
    choices: choices.barriersChoices,
    conditional: conditionals.hasBarrierTripConditional,
    validations: validations.optionalValidation
};

export const barriersDisabilityTrip: WidgetConfig.TextWidgetConfig = {
    ...defaultInputBase.infoTextBase,
    path: 'barriersDisabilityTrip',
    containsHtml: false,
    text: customLabels.barriersDisabilityTripCustomLabel,
    conditional: conditionals.hasBarrierDisabilityTripConditional
};

export const barriersDisabilityIntro: WidgetConfig.TextWidgetConfig = {
    ...defaultInputBase.infoTextBase,
    path: 'barriersDisabilityIntro',
    containsHtml: true,
    text: (t: TFunction) => t('barriers:barriersDisabilityIntro'),
    conditional: conditionals.hasBarrierDisabilityTripConditional
};

export const barriersDisabilityFrequency: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'barriersDisabilityFrequency',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('barriers:barriersDisabilityFrequency'),
    choices: choices.barriersChoices,
    conditional: conditionals.hasBarrierDisabilityTripConditional,
    validations: validations.optionalValidation
};

export const barriersDisabilityReliability: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'barriersDisabilityReliability',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('barriers:barriersDisabilityReliability'),
    choices: choices.barriersChoices,
    conditional: conditionals.hasBarrierDisabilityTripConditional,
    validations: validations.optionalValidation
};

export const barriersDisabilityWalk: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'barriersDisabilityWalk',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('barriers:barriersDisabilityWalk'),
    choices: choices.barriersChoices,
    conditional: conditionals.hasBarrierDisabilityTripConditional,
    validations: validations.optionalValidation
};

export const barriersDisabilityTime: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'barriersDisabilityTime',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('barriers:barriersDisabilityTime'),
    choices: choices.barriersChoices,
    conditional: conditionals.hasBarrierDisabilityTripConditional,
    validations: validations.optionalValidation
};

export const barriersDisabilityTransfer: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'barriersDisabilityTransfer',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('barriers:barriersDisabilityTransfer'),
    choices: choices.barriersChoices,
    conditional: conditionals.hasBarrierDisabilityTripConditional,
    validations: validations.optionalValidation
};

export const barriersDisabilitySecurity: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'barriersDisabilitySecurity',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('barriers:barriersDisabilitySecurity'),
    choices: choices.barriersChoices,
    conditional: conditionals.hasBarrierDisabilityTripConditional,
    validations: validations.optionalValidation
};

export const barriersDisabilityUniversalAccessibility: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'barriersDisabilityUniversalAccessibility',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('barriers:barriersDisabilityUniversalAccessibility'),
    choices: choices.barriersChoices,
    conditional: conditionals.hasBarrierDisabilityTripConditional,
    validations: validations.optionalValidation
};

export const barriersDisabilityPlanning: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'barriersDisabilityPlanning',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('barriers:barriersDisabilityPlanning'),
    choices: choices.barriersChoices,
    conditional: conditionals.hasBarrierDisabilityTripConditional,
    validations: validations.optionalValidation
};

export const barriersDisabilityCourtesy: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'barriersDisabilityCourtesy',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('barriers:barriersDisabilityCourtesy'),
    choices: choices.barriersChoices,
    conditional: conditionals.hasBarrierDisabilityTripConditional,
    validations: validations.optionalValidation
};

export const buttonCompleteBarriersSection: WidgetConfig.ButtonWidgetConfig = {
    ...defaultInputBase.buttonNextBase,
    path: 'buttonCompleteBarriersSection',
    label: (t: TFunction) => t('barriers:buttonCompleteBarriersSection'),
    conditional: defaultConditional
};
