// This file was automatically generated by the Evolution Generator.
// The Evolution Generator is used to automate the creation of consistent, reliable code.
// Any changes made to this file will be overwritten.

import { TFunction } from 'i18next';
import _escape from 'lodash/escape';
import * as defaultInputBase from 'evolution-frontend/lib/components/inputs/defaultInputBase';
import { defaultConditional } from 'evolution-common/lib/services/widgets/conditionals/defaultConditional';
import * as WidgetConfig from 'evolution-common/lib/services/questionnaire/types';
import * as validations from 'evolution-common/lib/services/widgets/validations/validations';
import * as odSurveyHelpers from 'evolution-common/lib/services/odSurvey/helpers';
import * as choices from '../../common/choices';
import * as conditionals from '../../common/conditionals';
import * as customLabels from '../../common/customLabels';

export const barriersTrip: WidgetConfig.TextWidgetConfig = {
    ...defaultInputBase.infoTextBase,
    path: 'barriersTrip',
    containsHtml: true,
    text: customLabels.barriersTripCustomLabel,
    conditional: conditionals.hasBarrierTripConditional
};

export const barriersIntro: WidgetConfig.TextWidgetConfig = {
    ...defaultInputBase.infoTextBase,
    path: 'barriersIntro',
    containsHtml: true,
    text: (t: TFunction) => t('barriers:barriersIntro'),
    conditional: conditionals.hasBarrierTripConditional
};

export const barriersFrequency: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'barriersFrequency',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('barriers:barriersFrequency'),
    choices: choices.barriersChoices,
    conditional: conditionals.hasBarrierTripConditional,
    validations: validations.optionalValidation
};

export const barriersReliability: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'barriersReliability',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('barriers:barriersReliability'),
    choices: choices.barriersChoices,
    conditional: conditionals.hasBarrierTripConditional,
    validations: validations.optionalValidation
};

export const barriersWalk: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'barriersWalk',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('barriers:barriersWalk'),
    choices: choices.barriersChoices,
    conditional: conditionals.hasBarrierTripConditional,
    validations: validations.optionalValidation
};

export const barriersTime: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'barriersTime',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('barriers:barriersTime'),
    choices: choices.barriersChoices,
    conditional: conditionals.hasBarrierTripConditional,
    validations: validations.optionalValidation
};

export const barriersTransfer: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'barriersTransfer',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('barriers:barriersTransfer'),
    choices: choices.barriersChoices,
    conditional: conditionals.hasBarrierTripConditional,
    validations: validations.optionalValidation
};

export const barriersSecurity: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'barriersSecurity',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('barriers:barriersSecurity'),
    choices: choices.barriersChoices,
    conditional: conditionals.hasBarrierTripConditional,
    validations: validations.optionalValidation
};

export const barriersPlanning: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'barriersPlanning',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('barriers:barriersPlanning'),
    choices: choices.barriersChoices,
    conditional: conditionals.hasBarrierTripConditional,
    validations: validations.optionalValidation
};

export const buttonCompleteBarriersSection: WidgetConfig.ButtonWidgetConfig = {
    ...defaultInputBase.buttonNextBase,
    path: 'buttonCompleteBarriersSection',
    label: (t: TFunction) => t('barriers:buttonCompleteBarriersSection'),
    conditional: defaultConditional
};
