// This file was automatically generated by the Evolution Generator.
// The Evolution Generator is used to automate the creation of consistent, reliable code.
// Any changes made to this file will be overwritten.

import { SectionConfig } from 'evolution-common/lib/services/questionnaire/types';

export const widgetsNames: SectionConfig['widgets'] = [
    'barriersTrip',
    'barriersIntro',
    'barriersFrequency',
    'barriersReliability',
    'barriersWalk',
    'barriersTime',
    'barriersTransfer',
    'barriersSecurity',
    'barriersPlanning',
    'barriersDisabilityTrip',
    'barriersDisabilityIntro',
    'barriersDisabilityFrequency',
    'barriersDisabilityReliability',
    'barriersDisabilityWalk',
    'barriersDisabilityTime',
    'barriersDisabilityTransfer',
    'barriersDisabilitySecurity',
    'barriersDisabilityUniversalAccessibility',
    'barriersDisabilityPlanning',
    'barriersDisabilityCourtesy',
    'buttonCompleteBarriersSection'
];
