// This file was automatically generated by the Evolution Generator.
// The Evolution Generator is used to automate the creation of consistent, reliable code.
// Any changes made to this file will be overwritten.

import { checkConditionals } from 'evolution-common/lib/services/widgets/conditionals/checkConditionals';
import { type WidgetConditional } from 'evolution-common/lib/services/questionnaire/types';
import * as odSurveyHelpers from 'evolution-common/lib/services/odSurvey/helpers';

export const hasHouseholdSize1Conditional: WidgetConditional = (interview) => {
    return checkConditionals({
        interview,
        conditionals: [
            {
                path: 'household.size',
                comparisonOperator: '===',
                value: 1
            }
        ]
    });
};

export const hasHouseholdSize2OrMoreConditional: WidgetConditional = (interview) => {
    return checkConditionals({
        interview,
        conditionals: [
            {
                path: 'household.size',
                comparisonOperator: '>=',
                value: 2
            }
        ]
    });
};

export const hasHouseholdSize2Conditional: WidgetConditional = (interview) => {
    return checkConditionals({
        interview,
        conditionals: [
            {
                path: 'household.size',
                comparisonOperator: '===',
                value: 2
            }
        ]
    });
};

export const hasHouseholdSize3OrMoreConditional: WidgetConditional = (interview) => {
    return checkConditionals({
        interview,
        conditionals: [
            {
                path: 'household.size',
                comparisonOperator: '>=',
                value: 3
            }
        ]
    });
};

export const hasOnePersonWithDisabilityOrHhSize1Conditional: WidgetConditional = (interview) => {
    return checkConditionals({
        interview,
        conditionals: [
            {
                path: 'household.atLeastOnePersonWithDisability',
                comparisonOperator: '===',
                value: 'yes'
            },
            {
                logicalOperator: '||',
                path: 'household.size',
                comparisonOperator: '===',
                value: 1
            }
        ]
    });
};

export const hasHouseholdBicycleConditional: WidgetConditional = (interview) => {
    return checkConditionals({
        interview,
        conditionals: [
            {
                path: 'household.bicycleNumber',
                comparisonOperator: '>=',
                value: 1
            }
        ]
    });
};

export const hasPreferNotToAnswerToSexAssignedConditional: WidgetConditional = (interview, path) => {
    const currentPersonId = odSurveyHelpers.getCurrentPersonId({ interview, path }); // Get the current person id
    return checkConditionals({
        interview,
        conditionals: [
            {
                path: `household.persons.${currentPersonId}.sexAssignedAtBirth`,
                comparisonOperator: '===',
                value: 'preferNotToAnswer'
            }
        ]
    });
};

export const ifAge3to5Conditional: WidgetConditional = (interview, path) => {
    const currentPersonId = odSurveyHelpers.getCurrentPersonId({ interview, path }); // Get the current person id
    return checkConditionals({
        interview,
        conditionals: [
            {
                path: `household.persons.${currentPersonId}.age`,
                comparisonOperator: '>=',
                value: 3
            },
            {
                logicalOperator: '&&',
                path: `household.persons.${currentPersonId}.age`,
                comparisonOperator: '<=',
                value: 5
            }
        ]
    });
};

export const ifAge4to13Conditional: WidgetConditional = (interview, path) => {
    const currentPersonId = odSurveyHelpers.getCurrentPersonId({ interview, path }); // Get the current person id
    return checkConditionals({
        interview,
        conditionals: [
            {
                path: `household.persons.${currentPersonId}.age`,
                comparisonOperator: '>=',
                value: 4
            },
            {
                logicalOperator: '&&',
                path: `household.persons.${currentPersonId}.age`,
                comparisonOperator: '<=',
                value: 13
            }
        ]
    });
};

export const ifAge4to15Conditional: WidgetConditional = (interview, path) => {
    const currentPersonId = odSurveyHelpers.getCurrentPersonId({ interview, path }); // Get the current person id
    return checkConditionals({
        interview,
        conditionals: [
            {
                path: `household.persons.${currentPersonId}.age`,
                comparisonOperator: '>=',
                value: 4
            },
            {
                logicalOperator: '&&',
                path: `household.persons.${currentPersonId}.age`,
                comparisonOperator: '<=',
                value: 15
            }
        ]
    });
};

export const ifAge5OrLessConditional: WidgetConditional = (interview, path) => {
    const currentPersonId = odSurveyHelpers.getCurrentPersonId({ interview, path }); // Get the current person id
    return checkConditionals({
        interview,
        conditionals: [
            {
                path: `household.persons.${currentPersonId}.age`,
                comparisonOperator: '<=',
                value: 5
            }
        ]
    });
};

export const ifAge5orMoreConditional: WidgetConditional = (interview, path) => {
    const currentPersonId = odSurveyHelpers.getCurrentPersonId({ interview, path }); // Get the current person id
    return checkConditionals({
        interview,
        conditionals: [
            {
                path: `household.persons.${currentPersonId}.age`,
                comparisonOperator: '>=',
                value: 5
            }
        ]
    });
};

export const ifAge6OrMoreConditional: WidgetConditional = (interview, path) => {
    const currentPersonId = odSurveyHelpers.getCurrentPersonId({ interview, path }); // Get the current person id
    return checkConditionals({
        interview,
        conditionals: [
            {
                path: `household.persons.${currentPersonId}.age`,
                comparisonOperator: '>=',
                value: 6
            }
        ]
    });
};

export const ifAge11OrMoreConditional: WidgetConditional = (interview, path) => {
    const currentPersonId = odSurveyHelpers.getCurrentPersonId({ interview, path }); // Get the current person id
    return checkConditionals({
        interview,
        conditionals: [
            {
                path: `household.persons.${currentPersonId}.age`,
                comparisonOperator: '>=',
                value: 11
            }
        ]
    });
};

export const ifAge14orMoreConditional: WidgetConditional = (interview, path) => {
    const currentPersonId = odSurveyHelpers.getCurrentPersonId({ interview, path }); // Get the current person id
    return checkConditionals({
        interview,
        conditionals: [
            {
                path: `household.persons.${currentPersonId}.age`,
                comparisonOperator: '>=',
                value: 14
            }
        ]
    });
};

export const ifAge15OrLessConditional: WidgetConditional = (interview, path) => {
    const currentPersonId = odSurveyHelpers.getCurrentPersonId({ interview, path }); // Get the current person id
    return checkConditionals({
        interview,
        conditionals: [
            {
                path: `household.persons.${currentPersonId}.age`,
                comparisonOperator: '<=',
                value: 15
            },
            {
                logicalOperator: '&&',
                path: `household.persons.${currentPersonId}.age`,
                comparisonOperator: '!==',
                value: null
            }
        ]
    });
};

export const ifAge15OrMoreConditional: WidgetConditional = (interview, path) => {
    const currentPersonId = odSurveyHelpers.getCurrentPersonId({ interview, path }); // Get the current person id
    return checkConditionals({
        interview,
        conditionals: [
            {
                path: `household.persons.${currentPersonId}.age`,
                comparisonOperator: '>=',
                value: 15
            }
        ]
    });
};

export const ifAge16OrMoreConditional: WidgetConditional = (interview, path) => {
    const currentPersonId = odSurveyHelpers.getCurrentPersonId({ interview, path }); // Get the current person id
    return checkConditionals({
        interview,
        conditionals: [
            {
                path: `household.persons.${currentPersonId}.age`,
                comparisonOperator: '>=',
                value: 16
            }
        ]
    });
};

export const ifAge16OrLessConditional: WidgetConditional = (interview, path) => {
    const currentPersonId = odSurveyHelpers.getCurrentPersonId({ interview, path }); // Get the current person id
    return checkConditionals({
        interview,
        conditionals: [
            {
                path: `household.persons.${currentPersonId}.age`,
                comparisonOperator: '<=',
                value: 16
            },
            {
                logicalOperator: '&&',
                path: `household.persons.${currentPersonId}.age`,
                comparisonOperator: '!==',
                value: null
            }
        ]
    });
};

export const ifAge40OrMoreConditional: WidgetConditional = (interview, path) => {
    const currentPersonId = odSurveyHelpers.getCurrentPersonId({ interview, path }); // Get the current person id
    return checkConditionals({
        interview,
        conditionals: [
            {
                path: `household.persons.${currentPersonId}.age`,
                comparisonOperator: '>=',
                value: 40
            }
        ]
    });
};

export const ifAge64OrLessConditional: WidgetConditional = (interview, path) => {
    const currentPersonId = odSurveyHelpers.getCurrentPersonId({ interview, path }); // Get the current person id
    return checkConditionals({
        interview,
        conditionals: [
            {
                path: `household.persons.${currentPersonId}.age`,
                comparisonOperator: '<=',
                value: 64
            }
        ]
    });
};

export const ifAge65OrMoreConditional: WidgetConditional = (interview, path) => {
    const currentPersonId = odSurveyHelpers.getCurrentPersonId({ interview, path }); // Get the current person id
    return checkConditionals({
        interview,
        conditionals: [
            {
                path: `household.persons.${currentPersonId}.age`,
                comparisonOperator: '>=',
                value: 65
            }
        ]
    });
};

export const hasDrivingLicenseConditional: WidgetConditional = (interview, path) => {
    const currentPersonId = odSurveyHelpers.getCurrentPersonId({ interview, path }); // Get the current person id
    return checkConditionals({
        interview,
        conditionals: [
            {
                path: `household.persons.${currentPersonId}.drivingLicenseOwnership`,
                comparisonOperator: '===',
                value: 'yes'
            }
        ]
    });
};

export const isWorkerConditional: WidgetConditional = (interview, path) => {
    const currentPersonId = odSurveyHelpers.getCurrentPersonId({ interview, path }); // Get the current person id
    return checkConditionals({
        interview,
        conditionals: [
            {
                path: `household.persons.${currentPersonId}.occupation`,
                comparisonOperator: '===',
                value: 'fullTimeWorker'
            },
            {
                logicalOperator: '||',
                path: `household.persons.${currentPersonId}.occupation`,
                comparisonOperator: '===',
                value: 'partTimeWorker'
            },
            {
                logicalOperator: '||',
                path: `household.persons.${currentPersonId}.occupation`,
                comparisonOperator: '===',
                value: 'workerAndStudent'
            }
        ]
    });
};

export const isStudentConditional: WidgetConditional = (interview, path) => {
    const currentPersonId = odSurveyHelpers.getCurrentPersonId({ interview, path }); // Get the current person id
    return checkConditionals({
        interview,
        conditionals: [
            {
                path: `household.persons.${currentPersonId}.occupation`,
                comparisonOperator: '===',
                value: 'fullTimeStudent'
            },
            {
                logicalOperator: '||',
                path: `household.persons.${currentPersonId}.occupation`,
                comparisonOperator: '===',
                value: 'partTimeStudent'
            },
            {
                logicalOperator: '||',
                path: `household.persons.${currentPersonId}.occupation`,
                comparisonOperator: '===',
                value: 'workerAndStudent'
            }
        ]
    });
};

export const hasWorkingLocationConditional: WidgetConditional = (interview, path) => {
    const currentPersonId = odSurveyHelpers.getCurrentPersonId({ interview, path }); // Get the current person id
    return checkConditionals({
        interview,
        conditionals: [
            {
                path: `household.persons.${currentPersonId}.workPlaceType`,
                comparisonOperator: '===',
                value: 'onLocation'
            },
            {
                logicalOperator: '||',
                path: `household.persons.${currentPersonId}.workPlaceType`,
                comparisonOperator: '===',
                value: 'hybrid'
            },
            {
                logicalOperator: '||',
                path: `household.persons.${currentPersonId}.workPlaceType`,
                comparisonOperator: '===',
                value: 'onTheRoadWithUsualPlace'
            },
            {
                logicalOperator: '||',
                path: `household.persons.${currentPersonId}.workPlaceTypeBeforeLeave`,
                comparisonOperator: '===',
                value: 'onLocation'
            },
            {
                logicalOperator: '||',
                path: `household.persons.${currentPersonId}.workPlaceTypeBeforeLeave`,
                comparisonOperator: '===',
                value: 'hybrid'
            },
            {
                logicalOperator: '||',
                path: `household.persons.${currentPersonId}.workPlaceTypeBeforeLeave`,
                comparisonOperator: '===',
                value: 'onTheRoadWithUsualPlace'
            }
        ]
    });
};

export const personDisabilityIsNotPreferNotToAnswer: WidgetConditional = (interview, path) => {
    const currentPersonId = odSurveyHelpers.getCurrentPersonId({ interview, path }); // Get the current person id
    return checkConditionals({
        interview,
        conditionals: [
            {
                path: `household.persons.${currentPersonId}.disabilities`,
                comparisonOperator: '===',
                value: null
            },
            {
                logicalOperator: '||',
                path: `household.persons.${currentPersonId}.disabilities`,
                comparisonOperator: '!==',
                value: 'preferNotToAnswer'
            }
        ]
    });
};

export const personDisabilityIsOtherConditional: WidgetConditional = (interview, path) => {
    const currentPersonId = odSurveyHelpers.getCurrentPersonId({ interview, path }); // Get the current person id
    return checkConditionals({
        interview,
        conditionals: [
            {
                path: `household.persons.${currentPersonId}.disabilities`,
                comparisonOperator: '===',
                value: 'other'
            }
        ]
    });
};

export const personMobilityDeviceNotExclusiveAnswer: WidgetConditional = (interview, path) => {
    const currentPersonId = odSurveyHelpers.getCurrentPersonId({ interview, path }); // Get the current person id
    return checkConditionals({
        interview,
        conditionals: [
            {
                path: `household.persons.${currentPersonId}.mobilityAssistiveDevices`,
                comparisonOperator: '===',
                value: null
            },
            {
                logicalOperator: '||',
                path: `household.persons.${currentPersonId}.mobilityAssistiveDevices`,
                comparisonOperator: '!==',
                value: 'noSpecificDevice',
                parentheses: '('
            },
            {
                logicalOperator: '&&',
                path: `household.persons.${currentPersonId}.mobilityAssistiveDevices`,
                comparisonOperator: '!==',
                value: 'preferNotToAnswer',
                parentheses: ')'
            }
        ]
    });
};

export const personMobilityDeviceNotPreferNotToAnswer: WidgetConditional = (interview, path) => {
    const currentPersonId = odSurveyHelpers.getCurrentPersonId({ interview, path }); // Get the current person id
    return checkConditionals({
        interview,
        conditionals: [
            {
                path: `household.persons.${currentPersonId}.mobilityAssistiveDevices`,
                comparisonOperator: '===',
                value: null
            },
            {
                logicalOperator: '||',
                path: `household.persons.${currentPersonId}.mobilityAssistiveDevices`,
                comparisonOperator: '!==',
                value: 'preferNotToAnswer'
            }
        ]
    });
};

export const personMobilityDeviceNotNone: WidgetConditional = (interview, path) => {
    const currentPersonId = odSurveyHelpers.getCurrentPersonId({ interview, path }); // Get the current person id
    return checkConditionals({
        interview,
        conditionals: [
            {
                path: `household.persons.${currentPersonId}.mobilityAssistiveDevices`,
                comparisonOperator: '===',
                value: null
            },
            {
                logicalOperator: '||',
                path: `household.persons.${currentPersonId}.mobilityAssistiveDevices`,
                comparisonOperator: '!==',
                value: 'noSpecificDevice'
            }
        ]
    });
};

export const personAssistiveDevicesIsOtherConditional: WidgetConditional = (interview, path) => {
    const currentPersonId = odSurveyHelpers.getCurrentPersonId({ interview, path }); // Get the current person id
    return checkConditionals({
        interview,
        conditionals: [
            {
                path: `household.persons.${currentPersonId}.mobilityAssistiveDevices`,
                comparisonOperator: '===',
                value: 'other'
            }
        ]
    });
};

export const acceptsToBeContactedForHelp: WidgetConditional = (interview) => {
    return checkConditionals({
        interview,
        conditionals: [
            {
                path: 'acceptToBeContactedForHelp',
                comparisonOperator: '===',
                value: 'yes'
            },
            {
                logicalOperator: '||',
                path: 'wantToParticipateToDraw',
                comparisonOperator: '===',
                value: 'yes'
            }
        ]
    });
};

export const wantToParticipateInOtherSurveysChaireMobiliteConditional: WidgetConditional = (interview) => {
    return checkConditionals({
        interview,
        conditionals: [
            {
                path: 'end.wouldLikeToParticipateInOtherSurveysChaireMobilite',
                comparisonOperator: '===',
                value: 'yes'
            }
        ]
    });
};

export const householdHasCars: WidgetConditional = (interview) => {
    return checkConditionals({
        interview,
        conditionals: [
            {
                path: 'household.carNumber',
                comparisonOperator: '>=',
                value: 1
            }
        ]
    });
};

export const onTheRoadUsualWorkplace: WidgetConditional = (interview, path) => {
    const currentPersonId = odSurveyHelpers.getCurrentPersonId({ interview, path }); // Get the current person id
    return checkConditionals({
        interview,
        conditionals: [
            {
                path: `household.persons.${currentPersonId}.workPlaceType`,
                comparisonOperator: '===',
                value: 'onTheRoadWithUsualPlace'
            }
        ]
    });
};

export const personWorkDaysConditional: WidgetConditional = (interview, path) => {
    const currentPersonId = odSurveyHelpers.getCurrentPersonId({ interview, path }); // Get the current person id
    return checkConditionals({
        interview,
        conditionals: [
            {
                path: `household.persons.${currentPersonId}.workPlaceType`,
                comparisonOperator: '===',
                value: 'hybrid'
            }
        ]
    });
};

export const personWorkTripDaysConditional: WidgetConditional = (interview, path) => {
    const currentPersonId = odSurveyHelpers.getCurrentPersonId({ interview, path }); // Get the current person id
    return checkConditionals({
        interview,
        conditionals: [
            {
                path: `household.persons.${currentPersonId}.workPlaceType`,
                comparisonOperator: '===',
                value: 'hybrid',
                parentheses: '('
            },
            {
                logicalOperator: '&&',
                path: `household.persons.${currentPersonId}.workDays`,
                comparisonOperator: '>',
                value: 0,
                parentheses: ')'
            },
            {
                logicalOperator: '||',
                path: `household.persons.${currentPersonId}.workPlaceType`,
                comparisonOperator: '===',
                value: 'onLocation'
            },
            {
                logicalOperator: '||',
                path: `household.persons.${currentPersonId}.workPlaceType`,
                comparisonOperator: '===',
                value: 'onTheRoadWithUsualPlace'
            },
            {
                logicalOperator: '||',
                path: `household.persons.${currentPersonId}.workPlaceType`,
                comparisonOperator: '===',
                value: 'onTheRoadWithoutUsualPlace'
            }
        ]
    });
};

export const hasDisabilityConditional: WidgetConditional = (interview, path) => {
    const currentPersonId = odSurveyHelpers.getCurrentPersonId({ interview, path }); // Get the current person id
    return checkConditionals({
        interview,
        conditionals: [
            {
                path: `household.persons.${currentPersonId}.hasDisability`,
                comparisonOperator: '===',
                value: 'yes'
            }
        ]
    });
};

export const paratransitFrequenciesConditional: WidgetConditional = (interview, path) => {
    const currentPersonId = odSurveyHelpers.getCurrentPersonId({ interview, path }); // Get the current person id
    return checkConditionals({
        interview,
        conditionals: [
            {
                path: `household.persons.${currentPersonId}.useParatransit`,
                comparisonOperator: '===',
                value: 'yes'
            },
            {
                logicalOperator: '&&',
                path: 'ep.exclusive',
                comparisonOperator: '===',
                value: 'householdType',
                parentheses: '('
            },
            {
                logicalOperator: '||',
                path: 'ep.exclusive',
                comparisonOperator: '===',
                value: 'omission'
            },
            {
                logicalOperator: '||',
                path: 'ep.exclusive',
                comparisonOperator: '===',
                value: 'paidParking'
            },
            {
                logicalOperator: '||',
                path: 'ep.exclusive',
                comparisonOperator: '===',
                value: 'respect',
                parentheses: ')'
            }
        ]
    });
};

export const doesNotUseTransitConditional: WidgetConditional = (interview, path) => {
    const currentPersonId = odSurveyHelpers.getCurrentPersonId({ interview, path }); // Get the current person id
    return checkConditionals({
        interview,
        conditionals: [
            {
                path: `household.persons.${currentPersonId}.usedTransitInLast30Days`,
                comparisonOperator: '===',
                value: 'no'
            }
        ]
    });
};

export const wantToParticipateInLongDistanceSurveyConditional: WidgetConditional = (interview) => {
    return checkConditionals({
        interview,
        conditionals: [
            {
                path: 'household.wouldLikeToParticipateToLongDistanceSurvey',
                comparisonOperator: '===',
                value: 'yes'
            }
        ]
    });
};

export const madeLongDistanceTripsConditional: WidgetConditional = (interview) => {
    return checkConditionals({
        interview,
        conditionals: [
            {
                path: 'household.madeLongDistanceTripsInLastYear',
                comparisonOperator: '===',
                value: 'yes'
            }
        ]
    });
};

export const workOnTheRoadConditional: WidgetConditional = (interview, path) => {
    const relativePath = path.substring(0, path.lastIndexOf('.')); // Remove the last key from the path
    const currentPersonId = odSurveyHelpers.getCurrentPersonId({ interview, path }); // Get the current person id
    return checkConditionals({
        interview,
        conditionals: [
            {
                path: `${relativePath}.activity`,
                comparisonOperator: '===',
                value: 'workOnTheRoad'
            },
            {
                logicalOperator: '&&',
                path: `household.persons.${currentPersonId}.workPlaceType`,
                comparisonOperator: '===',
                value: 'onTheRoadWithUsualPlace'
            }
        ]
    });
};

export const personDidTripsConditional: WidgetConditional = (interview, path) => {
    const currentPersonId = odSurveyHelpers.getCurrentPersonId({ interview, path }); // Get the current person id
    const currentJourneyId = odSurveyHelpers.getCurrentJourneyId({ interview, path }); // Get the current journey id
    return checkConditionals({
        interview,
        conditionals: [
            {
                path: `household.persons.${currentPersonId}.journeys.${currentJourneyId}.personDidTrips`,
                comparisonOperator: '===',
                value: 'yes'
            },
            {
                logicalOperator: '||',
                path: `household.persons.${currentPersonId}.journeys.${currentJourneyId}.personDidTripsConfirm`,
                comparisonOperator: '===',
                value: 'yes'
            }
        ]
    });
};

export const returnedHomeConditional: WidgetConditional = (interview, path) => {
    const currentPersonId = odSurveyHelpers.getCurrentPersonId({ interview, path }); // Get the current person id
    const currentJourneyId = odSurveyHelpers.getCurrentJourneyId({ interview, path }); // Get the current journey id
    return checkConditionals({
        interview,
        conditionals: [
            {
                path: `household.persons.${currentPersonId}.journeys.${currentJourneyId}.departurePlaceOther`,
                comparisonOperator: '===',
                value: 'hotelForWork'
            },
            {
                logicalOperator: '||',
                path: `household.persons.${currentPersonId}.journeys.${currentJourneyId}.departurePlaceOther`,
                comparisonOperator: '===',
                value: 'hotelForVacation'
            }
        ]
    });
};

export const outOfTerritoryMembersConditional: WidgetConditional = (interview, path) => {
    const currentPersonId = odSurveyHelpers.getCurrentPersonId({ interview, path }); // Get the current person id
    const currentJourneyId = odSurveyHelpers.getCurrentJourneyId({ interview, path }); // Get the current journey id
    return checkConditionals({
        interview,
        conditionals: [
            {
                path: `household.persons.${currentPersonId}.journeys.${currentJourneyId}.departurePlaceOther`,
                comparisonOperator: '===',
                value: 'hotelForVacation'
            },
            {
                logicalOperator: '&&',
                path: 'household.size',
                comparisonOperator: '>=',
                value: 2
            },
            {
                logicalOperator: '&&',
                path: `household.persons.${currentPersonId}.journeys.${currentJourneyId}.returnedHome`,
                comparisonOperator: '===',
                value: 'no'
            }
        ]
    });
};

export const isCurrentSegmentNotTransitBusConditional: WidgetConditional = (interview, path) => {
    const currentPersonId = odSurveyHelpers.getCurrentPersonId({ interview, path }); // Get the current person id
    const currentJourneyId = odSurveyHelpers.getCurrentJourneyId({ interview, path }); // Get the current journey id
    const currentTripId = odSurveyHelpers.getCurrentTripId({ interview, path }); // Get the current trip id
    const currentSegmentId = odSurveyHelpers.getCurrentSegmentId({ interview, path }); // Get the current segment id
    return checkConditionals({
        interview,
        conditionals: [
            {
                path: `household.persons.${currentPersonId}.journeys.${currentJourneyId}.trips.${currentTripId}.segments.${currentSegmentId}.mode`,
                comparisonOperator: '!==',
                value: 'transitBus'
            }
        ]
    });
};

export const subwayConditional: WidgetConditional = (interview, path) => {
    const currentPersonId = odSurveyHelpers.getCurrentPersonId({ interview, path }); // Get the current person id
    const currentJourneyId = odSurveyHelpers.getCurrentJourneyId({ interview, path }); // Get the current journey id
    const currentTripId = odSurveyHelpers.getCurrentTripId({ interview, path }); // Get the current trip id
    const currentSegmentId = odSurveyHelpers.getCurrentSegmentId({ interview, path }); // Get the current segment id
    return checkConditionals({
        interview,
        conditionals: [
            {
                path: `household.persons.${currentPersonId}.journeys.${currentJourneyId}.trips.${currentTripId}.segments.${currentSegmentId}.mode`,
                comparisonOperator: '===',
                value: 'transitRRT'
            }
        ]
    });
};

export const trainConditional: WidgetConditional = (interview, path) => {
    const currentPersonId = odSurveyHelpers.getCurrentPersonId({ interview, path }); // Get the current person id
    const currentJourneyId = odSurveyHelpers.getCurrentJourneyId({ interview, path }); // Get the current journey id
    const currentTripId = odSurveyHelpers.getCurrentTripId({ interview, path }); // Get the current trip id
    const currentSegmentId = odSurveyHelpers.getCurrentSegmentId({ interview, path }); // Get the current segment id
    return checkConditionals({
        interview,
        conditionals: [
            {
                path: `household.persons.${currentPersonId}.journeys.${currentJourneyId}.trips.${currentTripId}.segments.${currentSegmentId}.mode`,
                comparisonOperator: '===',
                value: 'transitRegionalRail'
            }
        ]
    });
};

export const remConditional: WidgetConditional = (interview, path) => {
    const currentPersonId = odSurveyHelpers.getCurrentPersonId({ interview, path }); // Get the current person id
    const currentJourneyId = odSurveyHelpers.getCurrentJourneyId({ interview, path }); // Get the current journey id
    const currentTripId = odSurveyHelpers.getCurrentTripId({ interview, path }); // Get the current trip id
    const currentSegmentId = odSurveyHelpers.getCurrentSegmentId({ interview, path }); // Get the current segment id
    return checkConditionals({
        interview,
        conditionals: [
            {
                path: `household.persons.${currentPersonId}.journeys.${currentJourneyId}.trips.${currentTripId}.segments.${currentSegmentId}.mode`,
                comparisonOperator: '===',
                value: 'transitLRRT'
            }
        ]
    });
};

export const busConditional: WidgetConditional = (interview, path) => {
    const currentPersonId = odSurveyHelpers.getCurrentPersonId({ interview, path }); // Get the current person id
    const currentJourneyId = odSurveyHelpers.getCurrentJourneyId({ interview, path }); // Get the current journey id
    const currentTripId = odSurveyHelpers.getCurrentTripId({ interview, path }); // Get the current trip id
    const currentSegmentId = odSurveyHelpers.getCurrentSegmentId({ interview, path }); // Get the current segment id
    return checkConditionals({
        interview,
        conditionals: [
            {
                path: `household.persons.${currentPersonId}.journeys.${currentJourneyId}.trips.${currentTripId}.segments.${currentSegmentId}.mode`,
                comparisonOperator: '===',
                value: 'transitBus'
            }
        ]
    });
};

export const subwayLineConditional: WidgetConditional = (interview, path) => {
    const currentPersonId = odSurveyHelpers.getCurrentPersonId({ interview, path }); // Get the current person id
    const currentJourneyId = odSurveyHelpers.getCurrentJourneyId({ interview, path }); // Get the current journey id
    const currentTripId = odSurveyHelpers.getCurrentTripId({ interview, path }); // Get the current trip id
    const currentSegmentId = odSurveyHelpers.getCurrentSegmentId({ interview, path }); // Get the current segment id
    return checkConditionals({
        interview,
        conditionals: [
            {
                path: `household.persons.${currentPersonId}.journeys.${currentJourneyId}.trips.${currentTripId}.segments.${currentSegmentId}.subwayStationStart`,
                comparisonOperator: '===',
                value: 'berriUqam'
            },
            {
                logicalOperator: '&&',
                path: `household.persons.${currentPersonId}.journeys.${currentJourneyId}.trips.${currentTripId}.segments.${currentSegmentId}.subwayStationEnd`,
                comparisonOperator: '===',
                value: 'lionelGroulx'
            },
            {
                logicalOperator: '||',
                path: `household.persons.${currentPersonId}.journeys.${currentJourneyId}.trips.${currentTripId}.segments.${currentSegmentId}.subwayStationStart`,
                comparisonOperator: '===',
                value: 'lionelGroulx',
                parentheses: '('
            },
            {
                logicalOperator: '&&',
                path: `household.persons.${currentPersonId}.journeys.${currentJourneyId}.trips.${currentTripId}.segments.${currentSegmentId}.subwayStationEnd`,
                comparisonOperator: '===',
                value: 'berriUqam',
                parentheses: ')'
            },
            {
                logicalOperator: '||',
                path: `household.persons.${currentPersonId}.journeys.${currentJourneyId}.trips.${currentTripId}.segments.${currentSegmentId}.subwayStationStart`,
                comparisonOperator: '===',
                value: 'jeanDrapeau',
                parentheses: '('
            },
            {
                logicalOperator: '&&',
                path: `household.persons.${currentPersonId}.journeys.${currentJourneyId}.trips.${currentTripId}.segments.${currentSegmentId}.subwayStationEnd`,
                comparisonOperator: '===',
                value: 'lionelGroulx',
                parentheses: ')'
            },
            {
                logicalOperator: '||',
                path: `household.persons.${currentPersonId}.journeys.${currentJourneyId}.trips.${currentTripId}.segments.${currentSegmentId}.subwayStationStart`,
                comparisonOperator: '===',
                value: 'lionelGroulx',
                parentheses: '('
            },
            {
                logicalOperator: '&&',
                path: `household.persons.${currentPersonId}.journeys.${currentJourneyId}.trips.${currentTripId}.segments.${currentSegmentId}.subwayStationEnd`,
                comparisonOperator: '===',
                value: 'jeanDrapeau',
                parentheses: ')'
            },
            {
                logicalOperator: '||',
                path: `household.persons.${currentPersonId}.journeys.${currentJourneyId}.trips.${currentTripId}.segments.${currentSegmentId}.subwayStationStart`,
                comparisonOperator: '===',
                value: 'longueuilUniversiteDeSherbrooke',
                parentheses: '('
            },
            {
                logicalOperator: '&&',
                path: `household.persons.${currentPersonId}.journeys.${currentJourneyId}.trips.${currentTripId}.segments.${currentSegmentId}.subwayStationEnd`,
                comparisonOperator: '===',
                value: 'lionelGroulx',
                parentheses: ')'
            },
            {
                logicalOperator: '||',
                path: `household.persons.${currentPersonId}.journeys.${currentJourneyId}.trips.${currentTripId}.segments.${currentSegmentId}.subwayStationStart`,
                comparisonOperator: '===',
                value: 'lionelGroulx',
                parentheses: '('
            },
            {
                logicalOperator: '&&',
                path: `household.persons.${currentPersonId}.journeys.${currentJourneyId}.trips.${currentTripId}.segments.${currentSegmentId}.subwayStationEnd`,
                comparisonOperator: '===',
                value: 'longueuilUniversiteDeSherbrooke',
                parentheses: ')'
            }
        ]
    });
};

export const householdWithTwoWheelConditional: WidgetConditional = (interview) => {
    return checkConditionals({
        interview,
        conditionals: [
            {
                path: 'household.twoWheelNumber',
                comparisonOperator: '>=',
                value: 1
            }
        ]
    });
};

export const householdWithoutTwoWheelConditional: WidgetConditional = (interview) => {
    return checkConditionals({
        interview,
        conditionals: [
            {
                path: 'household.twoWheelNumber',
                comparisonOperator: '===',
                value: 0
            }
        ]
    });
};

export const hasSchoolLocationNotSetConditional: WidgetConditional = (interview, path) => {
    const currentPersonId = odSurveyHelpers.getCurrentPersonId({ interview, path }); // Get the current person id
    return checkConditionals({
        interview,
        conditionals: [
            {
                path: `household.persons.${currentPersonId}.hasSchoolPlace`,
                comparisonOperator: '===',
                value: 'yes'
            }
        ]
    });
};

export const carParkingHomeWithVehicleConditional: WidgetConditional = (interview) => {
    return checkConditionals({
        interview,
        conditionals: [
            {
                path: 'home.geography.properties.RA',
                comparisonOperator: '<=',
                value: 4
            },
            {
                logicalOperator: '&&',
                path: 'ep.exclusive',
                comparisonOperator: '===',
                value: 'freqAttitudinal',
                parentheses: '('
            },
            {
                logicalOperator: '||',
                path: 'ep.exclusive',
                comparisonOperator: '===',
                value: 'freqBrakes'
            },
            {
                logicalOperator: '||',
                path: 'ep.exclusive',
                comparisonOperator: '===',
                value: 'freqAttitudinalBrakes',
                parentheses: ')'
            },
            {
                logicalOperator: '&&',
                path: 'household.carNumber',
                comparisonOperator: '>=',
                value: 1,
                parentheses: '('
            },
            {
                logicalOperator: '||',
                path: 'household.twoWheelNumber',
                comparisonOperator: '>=',
                value: 1,
                parentheses: ')'
            }
        ]
    });
};

export const carParkingHomeWithoutVehicleConditional: WidgetConditional = (interview) => {
    return checkConditionals({
        interview,
        conditionals: [
            {
                path: 'home.geography.properties.RA',
                comparisonOperator: '<=',
                value: 4
            },
            {
                logicalOperator: '&&',
                path: 'ep.exclusive',
                comparisonOperator: '===',
                value: 'freqAttitudinal',
                parentheses: '('
            },
            {
                logicalOperator: '||',
                path: 'ep.exclusive',
                comparisonOperator: '===',
                value: 'freqBrakes'
            },
            {
                logicalOperator: '||',
                path: 'ep.exclusive',
                comparisonOperator: '===',
                value: 'freqAttitudinalBrakes',
                parentheses: ')'
            },
            {
                logicalOperator: '&&',
                path: 'household.carNumber',
                comparisonOperator: '===',
                value: 0
            },
            {
                logicalOperator: '&&',
                path: 'household.twoWheelNumber',
                comparisonOperator: '===',
                value: 0
            }
        ]
    });
};

export const sharingMobilitiesConditional: WidgetConditional = (interview) => {
    return checkConditionals({
        interview,
        valueWhenHidden: 'no',
        conditionals: [
            {
                path: 'household.size',
                comparisonOperator: '>=',
                value: 2
            },
            {
                logicalOperator: '&&',
                path: 'home.geography.properties.RA',
                comparisonOperator: '<=',
                value: 6
            }
        ]
    });
};

export const carsharingConditional: WidgetConditional = (interview, path) => {
    const currentPersonId = odSurveyHelpers.getCurrentPersonId({ interview, path }); // Get the current person id
    return checkConditionals({
        interview,
        conditionals: [
            {
                path: `household.persons.${currentPersonId}.drivingLicenseOwnership`,
                comparisonOperator: '===',
                value: 'yes'
            },
            {
                logicalOperator: '&&',
                path: 'household.carsharing',
                comparisonOperator: '===',
                value: 'yes',
                parentheses: '('
            },
            {
                logicalOperator: '||',
                path: 'home.geography.properties.RA',
                comparisonOperator: '<=',
                value: 6
            },
            {
                logicalOperator: '&&',
                path: 'household.size',
                comparisonOperator: '===',
                value: 1,
                parentheses: ')'
            }
        ]
    });
};

export const bikesharingConditional: WidgetConditional = (interview, path) => {
    const currentPersonId = odSurveyHelpers.getCurrentPersonId({ interview, path }); // Get the current person id
    return checkConditionals({
        interview,
        conditionals: [
            {
                path: `household.persons.${currentPersonId}.age`,
                comparisonOperator: '>=',
                value: 14
            },
            {
                logicalOperator: '&&',
                path: 'household.bikesharing',
                comparisonOperator: '===',
                value: 'yes',
                parentheses: '('
            },
            {
                logicalOperator: '||',
                path: 'home.geography.properties.RA',
                comparisonOperator: '<=',
                value: 6
            },
            {
                logicalOperator: '&&',
                path: 'household.size',
                comparisonOperator: '===',
                value: 1,
                parentheses: ')'
            }
        ]
    });
};

export const bikesharingMembershipConditional: WidgetConditional = (interview, path) => {
    const currentPersonId = odSurveyHelpers.getCurrentPersonId({ interview, path }); // Get the current person id
    return checkConditionals({
        interview,
        conditionals: [
            {
                path: `household.persons.${currentPersonId}.bikesharingUsage`,
                comparisonOperator: '===',
                value: 'yes'
            }
        ]
    });
};

export const transitPassConditional: WidgetConditional = (interview, path) => {
    const currentPersonId = odSurveyHelpers.getCurrentPersonId({ interview, path }); // Get the current person id
    return checkConditionals({
        interview,
        conditionals: [
            {
                path: `household.persons.${currentPersonId}.age`,
                comparisonOperator: '>=',
                value: 12
            },
            {
                logicalOperator: '&&',
                path: `household.persons.${currentPersonId}.usedTransitInLast30Days`,
                comparisonOperator: '===',
                value: 'yes'
            }
        ]
    });
};

export const transitFareConditional: WidgetConditional = (interview, path) => {
    const currentPersonId = odSurveyHelpers.getCurrentPersonId({ interview, path }); // Get the current person id
    return checkConditionals({
        interview,
        conditionals: [
            {
                path: `household.persons.${currentPersonId}.transitPass`,
                comparisonOperator: '===',
                value: 'transitPassARTM'
            }
        ]
    });
};

export const toddlerDaycareConditional: WidgetConditional = (interview) => {
    return checkConditionals({
        interview,
        conditionals: [
            {
                path: 'omissions.toddlerDaycare',
                comparisonOperator: '===',
                value: 'yes'
            }
        ]
    });
};

export const hasOmittedTripsConditional: WidgetConditional = (interview) => {
    return checkConditionals({
        interview,
        conditionals: [
            {
                path: 'ep.exclusive',
                comparisonOperator: '===',
                value: 'omission'
            }
        ]
    });
};

export const hasOmittedTripsSpecifyConditional: WidgetConditional = (interview) => {
    return checkConditionals({
        interview,
        conditionals: [
            {
                path: 'omissions.hasOmittedTrips',
                comparisonOperator: '===',
                value: 'yes'
            }
        ]
    });
};

export const householdTypeConditional: WidgetConditional = (interview) => {
    return checkConditionals({
        interview,
        conditionals: [
            {
                path: 'ep.exclusive',
                comparisonOperator: '===',
                value: 'householdType'
            },
            {
                logicalOperator: '&&',
                path: 'household.size',
                comparisonOperator: '>=',
                value: 2
            }
        ]
    });
};

export const householdTypeSpecifyConditional: WidgetConditional = (interview) => {
    return checkConditionals({
        interview,
        conditionals: [
            {
                path: 'household.type',
                comparisonOperator: '===',
                value: 'oneFamilyOnly'
            }
        ]
    });
};

export const didRespondForCorrectAssignedDateConditional: WidgetConditional = (interview) => {
    return checkConditionals({
        interview,
        conditionals: [
            {
                path: 'ep.exclusive',
                comparisonOperator: '===',
                value: 'respect'
            }
        ]
    });
};

export const didNotRespondForCorrectAssignedDateConditional: WidgetConditional = (interview) => {
    return checkConditionals({
        interview,
        conditionals: [
            {
                path: 'end.didRespondForCorrectAssignedDate',
                comparisonOperator: '===',
                value: 'no'
            }
        ]
    });
};

export const hasBarrierTripConditional: WidgetConditional = (interview) => {
    return checkConditionals({
        interview,
        conditionals: [
            {
                path: '_barriersTripPath',
                comparisonOperator: '!==',
                value: null
            }
        ]
    });
};

export const isBarriersDisabilityTripPersonAvailableConditional: WidgetConditional = (interview) => {
    return checkConditionals({
        interview,
        conditionals: [
            {
                path: 'barriersDisabilityIsPersonAvailable',
                comparisonOperator: '===',
                value: 'yes'
            }
        ]
    });
};

export const educationalAttainmentConditional: WidgetConditional = (interview, path) => {
    const currentPersonId = odSurveyHelpers.getCurrentPersonId({ interview, path }); // Get the current person id
    return checkConditionals({
        interview,
        conditionals: [
            {
                path: `household.persons.${currentPersonId}.occupation`,
                comparisonOperator: '===',
                value: 'fullTimeWorker'
            },
            {
                logicalOperator: '||',
                path: `household.persons.${currentPersonId}.occupation`,
                comparisonOperator: '===',
                value: 'partTimeWorker'
            },
            {
                logicalOperator: '||',
                path: `household.persons.${currentPersonId}.occupation`,
                comparisonOperator: '===',
                value: 'workerAndStudent'
            },
            {
                logicalOperator: '||',
                path: `household.persons.${currentPersonId}.occupation`,
                comparisonOperator: '===',
                value: 'unemployed'
            },
            {
                logicalOperator: '||',
                path: `household.persons.${currentPersonId}.occupation`,
                comparisonOperator: '===',
                value: 'parentalOrSickLeave'
            }
        ]
    });
};

export const enmpConditional: WidgetConditional = (interview) => {
    return checkConditionals({
        interview,
        conditionals: [
            {
                path: 'ep.exclusive',
                comparisonOperator: '===',
                value: 'mtmd'
            }
        ]
    });
};

export const isAccessCodeInvalidConditional: WidgetConditional = (interview) => {
    return checkConditionals({
        interview,
        conditionals: [
            {
                path: '_accessCodeConfirmed',
                comparisonOperator: '===',
                value: false
            }
        ]
    });
};

export const isAccessCodeNotValidConditional: WidgetConditional = (interview) => {
    return checkConditionals({
        interview,
        conditionals: [
            {
                path: '_accessCodeConfirmed',
                comparisonOperator: '===',
                value: false
            },
            {
                logicalOperator: '||',
                path: '_accessCodeConfirmed',
                comparisonOperator: '===',
                value: null
            }
        ]
    });
};

export const homeAddressIsPrefilledConditional: WidgetConditional = (interview) => {
    return checkConditionals({
        interview,
        conditionals: [
            {
                path: 'home._addressIsPrefilled',
                comparisonOperator: '===',
                value: true
            }
        ]
    });
};
