// This file was automatically generated by the Evolution Generator.
// The Evolution Generator is used to automate the creation of consistent, reliable code.
// Any changes made to this file will be overwritten.

import { isSectionCompleted } from 'evolution-common/lib/services/questionnaire/sections/navigationHelpers';
import { SectionConfig } from 'evolution-common/lib/services/questionnaire/types';
import { allPersonsTripDiariesCompleted } from '../../common/helper';
import { widgetsNames } from './widgetsNames';
import { shouldShowToddlerDayCareQuestions } from '../../common/customHelpers';
import { isPartialSample } from '../../common/commonHelpers';

export const currentSectionName: string = 'omissions';
const previousSectionName: SectionConfig['previousSection'] = 'personsTrips';
const nextSectionName: SectionConfig['nextSection'] = 'longDistance';
const parentSection = 'end';

const isSectionVisible = (interview) => {
    // Visible seulement si échantillon partiel est omission ou s'il faut montrer les questions de daycare
    return isPartialSample(interview, 'omission') || shouldShowToddlerDayCareQuestions(interview);
};

// Config for the section
export const sectionConfig: SectionConfig = {
    previousSection: previousSectionName,
    nextSection: nextSectionName,
    title: {
        fr: 'Oublis',
        en: 'Omissions'
    },
    navMenu: {
        type: 'hidden',
        parentSection: parentSection
    },
    widgets: widgetsNames,
    // Do some actions before the section is loaded
    // Allow to click on the section menu
    enableConditional: function (interview) {
        return allPersonsTripDiariesCompleted(interview);
    },
    // Determine if the current section is completed
    completionConditional: function (interview) {
        // Complété si échantillon partiel n'est pas omission, ni si les questions d'omission de déplacement garderie ne doivent pas être montrées ou effectivement complété
        return !isSectionVisible(interview) || isSectionCompleted({ interview, sectionName: currentSectionName });
    },
    isSectionVisible
};

export default sectionConfig;
