// This file was automatically generated by the Evolution Generator.
// The Evolution Generator is used to automate the creation of consistent, reliable code.
// Any changes made to this file will be overwritten.

import { isSectionCompleted } from 'evolution-common/lib/services/questionnaire/sections/navigationHelpers';
import { SectionConfig } from 'evolution-common/lib/services/questionnaire/types';
import { allPersonsTripDiariesCompleted } from '../../common/helper';
import { widgetsNames } from './widgetsNames';
import { isPartialSample } from '../../common/customHelpers';

export const currentSectionName: string = 'omissions';
const previousSectionName: SectionConfig['previousSection'] = 'personsTrips';
const nextSectionName: SectionConfig['nextSection'] = 'longDistance';
const parentSection = 'end';

// Config for the section
export const sectionConfig: SectionConfig = {
    previousSection: previousSectionName,
    nextSection: nextSectionName,
    title: {
        fr: 'Oublis',
        en: 'Omissions'
    },
    navMenu: {
        type: 'hidden',
        parentSection: parentSection
    },
    widgets: widgetsNames,
    // Do some actions before the section is loaded
    // Allow to click on the section menu
    enableConditional: function (interview) {
        return allPersonsTripDiariesCompleted(interview);
    },
    // Determine if the current section is completed
    completionConditional: function (interview) {
        // Complété si ep n'est pas omission ou effectivement complété
        return (
            !isPartialSample(interview, 'omission') ||
            isSectionCompleted({ interview, sectionName: currentSectionName })
        );
    },
    isSectionVisible: (interview) => {
        // Visible seulement is ep est omission
        return isPartialSample(interview, 'omission');
    }
};

export default sectionConfig;
