// This file was automatically generated by the Evolution Generator.
// The Evolution Generator is used to automate the creation of consistent, reliable code.
// Any changes made to this file will be overwritten.

import { isSectionCompleted } from 'evolution-common/lib/services/questionnaire/sections/navigationHelpers';
import { SectionConfig } from 'evolution-common/lib/services/questionnaire/types';
import { getResponse } from 'evolution-common/lib/utils/helpers';
import { allPersonsTripDiariesCompleted } from '../../common/helper';
import { widgetsNames } from './widgetsNames';

export const currentSectionName: string = 'omissions';
const previousSectionName: SectionConfig['previousSection'] = 'personsTrips';
const nextSectionName: SectionConfig['nextSection'] = 'longDistance';

// Config for the section
export const sectionConfig: SectionConfig = {
    previousSection: previousSectionName,
    nextSection: nextSectionName,
    title: {
        fr: 'Oublis',
        en: 'Omissions'
    },
    navMenu: {
        type: 'inNav',
        menuName: {
            fr: 'Oublis',
            en: 'Omissions'
        }
    },
    widgets: widgetsNames,
    // Do some actions before the section is loaded
    // Allow to click on the section menu
    enableConditional: function (interview) {
        return allPersonsTripDiariesCompleted(interview);
    },
    // Determine if the current section is completed
    completionConditional: function (interview) {
        return isSectionCompleted({ interview, sectionName: currentSectionName });
    },
    isSectionVisible: (interview) => {
        // Section visible seulement si ep exclusif est omission
        const exclusiveEP = getResponse(interview, 'ep.exclusive');
        return exclusiveEP === 'omission';
    }
};

export default sectionConfig;
