// This file was automatically generated by the Evolution Generator.
// The Evolution Generator is used to automate the creation of consistent, reliable code.
// Any changes made to this file will be overwritten.

import { TFunction } from 'i18next';
import * as defaultInputBase from 'evolution-frontend/lib/components/inputs/defaultInputBase';
import { defaultConditional } from 'evolution-common/lib/services/widgets/conditionals/defaultConditional';
import * as WidgetConfig from 'evolution-common/lib/services/questionnaire/types';
import * as validations from 'evolution-common/lib/services/widgets/validations/validations';
import * as choices from '../../common/choices';
import * as conditionals from '../../common/conditionals';
import * as customConditionals from '../../common/customConditionals';
import * as customHelpPopup from '../../common/customHelpPopup';
import * as customLabels from '../../common/customLabels';

// Adapter la phrase si un seul enfant de 0-4ans avec le nickname et age.
// Pour les conditions SI EP garderie ET au moins un enfant de 0-4ans ET aucun dép. reconduire/aller chercher à une garderie/CPE (shp)
export const toddlerDaycare: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'omissions.toddlerDaycare',
    twoColumns: false,
    containsHtml: true,
    label: customLabels.toddlerDaycareCustomLabel,
    helpPopup: customHelpPopup.toddlerDaycareHelpPopup,
    choices: choices.yesNo,
    conditional: customConditionals.toddlerDaycareCustomConditional,
    validations: validations.requiredValidation
};

// Adapter la phrase selon le nombre d'enfants
// Liste des membres du ménage + "une autre personne"
export const toddlerDaycareDropoff: WidgetConfig.InputCheckboxType = {
    ...defaultInputBase.inputCheckboxBase,
    path: 'omissions.toddlerDaycareDropoff',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('omissions:toddlerDaycareDropoff'),
    choices: choices.yesNo,
    conditional: conditionals.toddlerDaycareConditional,
    validations: validations.requiredValidation
};

export const toddlerDaycareDropoffMode: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'omissions.toddlerDaycareDropoffMode',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('omissions:toddlerDaycareDropoffMode'),
    choices: choices.toddlerDaycareMode,
    conditional: conditionals.toddlerDaycareConditional,
    validations: validations.requiredValidation
};

// Adapter la phrase selon le nombre d'enfants
// Liste des membres du ménage + "une autre personne"
export const toddlerDaycarePickup: WidgetConfig.InputCheckboxType = {
    ...defaultInputBase.inputCheckboxBase,
    path: 'omissions.toddlerDaycarePickup',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('omissions:toddlerDaycarePickup'),
    choices: choices.yesNo,
    conditional: conditionals.toddlerDaycareConditional,
    validations: validations.requiredValidation
};

export const toddlerDaycarePickupMode: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'omissions.toddlerDaycarePickupMode',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('omissions:toddlerDaycarePickupMode'),
    choices: choices.toddlerDaycareMode,
    conditional: conditionals.toddlerDaycareConditional,
    validations: validations.requiredValidation
};

export const hasOmittedTrips: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'omissions.hasOmittedTrips',
    twoColumns: false,
    containsHtml: true,
    label: customLabels.hasOmittedTripsCustomLabel,
    choices: choices.yesNo,
    conditional: conditionals.hasOmittedTripsConditional,
    validations: validations.requiredValidation
};

export const hasOmittedTripsIntro: WidgetConfig.TextWidgetConfig = {
    ...defaultInputBase.infoTextBase,
    path: 'omissions.hasOmittedTripsIntro',
    containsHtml: true,
    text: (t: TFunction) => t('omissions:hasOmittedTripsIntro'),
    conditional: conditionals.hasOmittedTripsSpecifyConditional
};

export const hasOmittedTripsActivity: WidgetConfig.InputCheckboxType = {
    ...defaultInputBase.inputCheckboxBase,
    path: 'omissions.hasOmittedTripsActivity',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('omissions:hasOmittedTripsActivity'),
    choices: choices.hasOmittedTripsActivities,
    conditional: conditionals.hasOmittedTripsSpecifyConditional,
    validations: validations.requiredValidation
};

export const hasOmittedTripsMode: WidgetConfig.InputCheckboxType = {
    ...defaultInputBase.inputCheckboxBase,
    path: 'omissions.hasOmittedTripsMode',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('omissions:hasOmittedTripsMode'),
    choices: choices.hasOmittedTripsModes,
    conditional: conditionals.hasOmittedTripsSpecifyConditional,
    validations: validations.requiredValidation
};

export const buttonCompleteOmissionsSection: WidgetConfig.ButtonWidgetConfig = {
    ...defaultInputBase.buttonNextBase,
    path: 'buttonCompleteOmissionsSection',
    label: (t: TFunction) => t('omissions:buttonCompleteOmissionsSection'),
    conditional: defaultConditional
};
