// This file was automatically generated by the Evolution Generator.
// The Evolution Generator is used to automate the creation of consistent, reliable code.
// Any changes made to this file will be overwritten.

import { test } from '@playwright/test';
import * as testHelpers from 'evolution-frontend/tests/ui-testing/testHelpers';
import * as surveyTestHelpers from 'evolution-frontend/tests/ui-testing/surveyTestHelpers';
import { SurveyObjectDetector } from 'evolution-frontend/tests/ui-testing/SurveyObjectDetectors';

const context = {
    page: null as any,
    objectDetector: new SurveyObjectDetector(),
    title: '',
    widgetTestCounters: {}
};

// Modify the CommonTestParameters type with survey parameters
export type CommonTestParametersModify = testHelpers.CommonTestParameters & {
    householdSize: number;
};

// Configure the tests to run in serial mode (one after the other)
test.describe.configure({ mode: 'serial' });

// Initialize the test page and add it to the context
test.beforeAll(async ({ browser }) => {
    context.page = await testHelpers.initializeTestPage(browser, context.objectDetector);
});

/********** Start the survey **********/

// Start the survey with email
surveyTestHelpers.startAndLoginWithEmail({
    context,
    title: '?',
    email: `test${Math.random().toString(36).substring(2, 15)}@test.com`,
    nextPageUrl: '?'
});
// Start the survey without email
surveyTestHelpers.startAndLoginAnonymously({ context, title: '?', hasUser: false });

/********** Tests Accesscode section **********/
export const fillAccesscodeSectionTests = ({ context, householdSize }: CommonTestParametersModify) => {
    // Verify the accessCode navigation is active
    testHelpers.verifyNavBarButtonStatus({ context, buttonText: 'accessCode', buttonStatus: 'active', isDisabled: false });

    // Progress bar test for accessCode section
    testHelpers.sectionProgressBarTest({ context, sectionName: 'accessCode', completionPercentage: 0 });

    // Test string widget accessCode with conditional isAccessCodeNotValidConditional
    /* @link file://./../src/survey/common/conditionals.tsx */
    testHelpers.inputVisibleTest({ context, path: 'accessCode', isVisible: true });
    testHelpers.inputStringTest({ context, path: 'accessCode', value: '?' });

    // Test checkbox widget accessCodeIsCorrectConfirmation with conditional isAccessCodeInvalidConditional with choices accessCodeConfirmChoices
    /* @link file://./../src/survey/common/conditionals.tsx */
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputVisibleTest({ context, path: 'accessCodeIsCorrect', isVisible: true });
    testHelpers.inputCheckboxTest({ context, path: 'accessCodeIsCorrect', values: ['?'] });

    // Test custom widget accessCode_confirm
    // Implement custom test
};

/********** Tests Home section **********/
export const fillHomeSectionTests = ({ context, householdSize }: CommonTestParametersModify) => {
    // Verify the home navigation is active
    testHelpers.verifyNavBarButtonStatus({ context, buttonText: 'home', buttonStatus: 'active', isDisabled: false });

    // Progress bar test for home section
    testHelpers.sectionProgressBarTest({ context, sectionName: 'home', completionPercentage: 0 });

    // Test radio widget acceptToBeContactedForHelp with choices yesNo
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputRadioTest({ context, path: 'acceptToBeContactedForHelp', value: '?' });

    // Test radio widget wantToParticipateToDraw with choices yesNo
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputRadioTest({ context, path: 'wantToParticipateToDraw', value: '?' });

    // Test infotext widget contactInformationIntro with conditional acceptsToBeContactedForHelp
    /* @link file://./../src/survey/common/conditionals.tsx */
    testHelpers.inputVisibleTest({ context, path: 'contactInformationIntro', isVisible: true });
    testHelpers.waitTextVisible({ context, text: '?' });

    // Test string widget contactEmail with conditional acceptsToBeContactedForHelp
    /* @link file://./../src/survey/common/conditionals.tsx */
    testHelpers.inputVisibleTest({ context, path: 'contactEmail', isVisible: true });
    testHelpers.inputStringTest({ context, path: 'contactEmail', value: '?' });

    // Test infotext widget homeIntro with conditional homeAddressIsPrefilledConditional
    /* @link file://./../src/survey/common/conditionals.tsx */
    testHelpers.inputVisibleTest({ context, path: 'homeIntro', isVisible: true });
    testHelpers.waitTextVisible({ context, text: '?' });

    // Test string widget homeAddress
    testHelpers.inputStringTest({ context, path: 'home.address', value: '?' });

    // Test string widget homeCity
    testHelpers.inputStringTest({ context, path: 'home.city', value: '?' });

    // Test string widget homePostalCode
    testHelpers.inputStringTest({ context, path: 'home.postalCode', value: '?' });

    // Test custom widget homeGeography
    // Implement custom test

    // Test radio widget homeIsMain with conditional sdrWithSecondaryHousesCustomConditional with choices homeIsMain
    /* @link file://./../src/survey/common/conditionals.tsx */
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputVisibleTest({ context, path: 'home.isMain', isVisible: true });
    testHelpers.inputRadioTest({ context, path: 'home.isMain', value: '?' });

    // Test radio widget householdOwnership with choices householdOwnershipChoices
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputRadioTest({ context, path: 'household.ownership', value: '?' });

    // Test radionumber widget householdSize

    // Test radionumber widget householdCarNumber

    // Test radionumber widget householdTwoWheelNumber

    // Test radionumber widget householdBicycleNumber

    // Test radionumber widget householdElectricBicycleNumber with conditional hasHouseholdBicycleConditional
    /* @link file://./../src/survey/common/conditionals.tsx */
    testHelpers.inputVisibleTest({ context, path: 'household.electricBicycleNumber', isVisible: true });

    // Test checkbox widget homeCarParkingsAvailableVehicleHousehold with conditional carParkingHomeWithVehicleConditional with choices carParkingsHome
    /* @link file://./../src/survey/common/conditionals.tsx */
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputVisibleTest({ context, path: 'home.carParkingAvailableVehicleHousehold', isVisible: true });
    testHelpers.inputCheckboxTest({ context, path: 'home.carParkingAvailableVehicleHousehold', values: ['?'] });

    // Test radio widget homeCarParkingsAvailableNoVehicleHousehold with conditional carParkingHomeWithoutVehicleConditional with choices yesNo
    /* @link file://./../src/survey/common/conditionals.tsx */
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputVisibleTest({ context, path: 'home.carParkingAvailableNoVehicleHousehold', isVisible: true });
    testHelpers.inputRadioTest({ context, path: 'home.carParkingAvailableNoVehicleHousehold', value: '?' });

    // Test radio widget householdCarsharing with conditional sharingMobilitiesConditional with choices yesNoDontKnow
    /* @link file://./../src/survey/common/conditionals.tsx */
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputVisibleTest({ context, path: 'household.carsharing', isVisible: true });
    testHelpers.inputRadioTest({ context, path: 'household.carsharing', value: '?' });

    // Test radio widget householdBikesharing with conditional sharingMobilitiesConditional with choices yesNoDontKnow
    /* @link file://./../src/survey/common/conditionals.tsx */
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputVisibleTest({ context, path: 'household.bikesharing', isVisible: true });
    testHelpers.inputRadioTest({ context, path: 'household.bikesharing', value: '?' });

    // Test radio widget householdAtLeastOnePersonWithDisability with conditional hasHouseholdSize2OrMoreConditional with choices yesNoPreferNotToAnswer
    /* @link file://./../src/survey/common/conditionals.tsx */
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputVisibleTest({ context, path: 'household.atLeastOnePersonWithDisability', isVisible: true });
    testHelpers.inputRadioTest({ context, path: 'household.atLeastOnePersonWithDisability', value: '?' });

    // Test nextbutton widget home_save
    testHelpers.inputNextButtonTest({ context, text: '?', nextPageUrl: '?' });

    // Verify the home navigation is completed
    testHelpers.verifyNavBarButtonStatus({ context, buttonText: 'home', buttonStatus: 'completed', isDisabled: false });
};

/********** Tests Household section **********/
export const fillHouseholdSectionTests = ({ context, householdSize }: CommonTestParametersModify) => {
    // Verify the household navigation is active
    testHelpers.verifyNavBarButtonStatus({ context, buttonText: 'household', buttonStatus: 'active', isDisabled: false });

    // Progress bar test for household section
    testHelpers.sectionProgressBarTest({ context, sectionName: 'household', completionPercentage: 0 });

    // Test custom widget householdMembers
    // Implement custom test

    // Test number widget personAge
    testHelpers.inputStringTest({ context, path: 'household.persons.${personId[0]}.age', value: '?' });

    // Test string widget personNickname with conditional hasPersonCount2OrMoreCustomConditional
    /* @link file://./../src/survey/common/conditionals.tsx */
    testHelpers.inputVisibleTest({ context, path: 'household.persons.${personId[0]}.nickname', isVisible: true });
    testHelpers.inputStringTest({ context, path: 'household.persons.${personId[0]}.nickname', value: '?' });

    // Test radio widget personGender with conditional ifAge5orMoreOrHhSize1Conditional with choices maleFemaleCustomPreferNotToAnswer
    /* @link file://./../src/survey/common/conditionals.tsx */
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputVisibleTest({ context, path: 'household.persons.${personId[0]}.gender', isVisible: true });
    testHelpers.inputRadioTest({ context, path: 'household.persons.${personId[0]}.gender', value: '?' });

    // Test radio widget personDrivingLicenseOwnership with conditional ifAge16OrMoreConditional with choices yesNoDontKnow
    /* @link file://./../src/survey/common/conditionals.tsx */
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputVisibleTest({ context, path: 'household.persons.${personId[0]}.drivingLicenseOwnership', isVisible: true });
    testHelpers.inputRadioTest({ context, path: 'household.persons.${personId[0]}.drivingLicenseOwnership', value: '?' });

    // Test radio widget personCarsharingMember with conditional carsharingConditional with choices yesNoDontKnow
    /* @link file://./../src/survey/common/conditionals.tsx */
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputVisibleTest({ context, path: 'household.persons.${personId[0]}.carsharingMember', isVisible: true });
    testHelpers.inputRadioTest({ context, path: 'household.persons.${personId[0]}.carsharingMember', value: '?' });

    // Test radio widget personBikesharingUsage with conditional bikesharingConditional with choices yesNoDontKnow
    /* @link file://./../src/survey/common/conditionals.tsx */
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputVisibleTest({ context, path: 'household.persons.${personId[0]}.bikesharingUsage', isVisible: true });
    testHelpers.inputRadioTest({ context, path: 'household.persons.${personId[0]}.bikesharingUsage', value: '?' });

    // Test radio widget personBikesharingMembership with conditional bikesharingMembershipConditional with choices bikesharingMembership
    /* @link file://./../src/survey/common/conditionals.tsx */
    /* @link file://./../src/survey/common/choices.tsx */
    // Widget not active

    // Test radio widget personUsedTransitInLast30Days with conditional ifAge5orMoreConditional with choices yesNoDontKnow
    /* @link file://./../src/survey/common/conditionals.tsx */
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputVisibleTest({ context, path: 'household.persons.${personId[0]}.usedTransitInLast30Days', isVisible: true });
    testHelpers.inputRadioTest({ context, path: 'household.persons.${personId[0]}.usedTransitInLast30Days', value: '?' });

    // Test checkbox widget personTransitPass with conditional transitPassConditional with choices transitPassType
    /* @link file://./../src/survey/common/conditionals.tsx */
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputVisibleTest({ context, path: 'household.persons.${personId[0]}.transitPass', isVisible: true });
    testHelpers.inputCheckboxTest({ context, path: 'household.persons.${personId[0]}.transitPass', values: ['?'] });

    // Test radio widget personTransitFare with conditional transitFareConditional with choices transitFareType
    /* @link file://./../src/survey/common/conditionals.tsx */
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputVisibleTest({ context, path: 'household.persons.${personId[0]}.transitFare', isVisible: true });
    testHelpers.inputRadioTest({ context, path: 'household.persons.${personId[0]}.transitFare', value: '?' });

    // Test checkbox widget personTransitFareWarning with conditional transitFareWarningCustomConditional with choices transitFareWarning
    /* @link file://./../src/survey/common/conditionals.tsx */
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputVisibleTest({ context, path: 'household.persons.${personId[0]}.transitFareWarning', isVisible: true });
    testHelpers.inputCheckboxTest({ context, path: 'household.persons.${personId[0]}.transitFareWarning', values: ['?'] });

    // Test radio widget personHasDisability with conditional hasOnePersonWithDisabilityOrHhSize1CustomConditional with choices yesNoPreferNotToAnswer
    /* @link file://./../src/survey/common/conditionals.tsx */
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputVisibleTest({ context, path: 'household.persons.${personId[0]}.hasDisability', isVisible: true });
    testHelpers.inputRadioTest({ context, path: 'household.persons.${personId[0]}.hasDisability', value: '?' });

    // Test checkbox widget personDisabilities with conditional hasDisabilityConditional with choices disabilities
    /* @link file://./../src/survey/common/conditionals.tsx */
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputVisibleTest({ context, path: 'household.persons.${personId[0]}.disabilities', isVisible: true });
    testHelpers.inputCheckboxTest({ context, path: 'household.persons.${personId[0]}.disabilities', values: ['?'] });

    // Test string widget personDisabilitiesSpecify with conditional personDisabilityIsOtherConditional
    /* @link file://./../src/survey/common/conditionals.tsx */
    testHelpers.inputVisibleTest({ context, path: 'household.persons.${personId[0]}.disabilitiesSpecify', isVisible: true });
    testHelpers.inputStringTest({ context, path: 'household.persons.${personId[0]}.disabilitiesSpecify', value: '?' });

    // Test checkbox widget personMobilityAssistiveDevices with conditional hasDisabilityConditional with choices mobilityAssistiveDevices
    /* @link file://./../src/survey/common/conditionals.tsx */
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputVisibleTest({ context, path: 'household.persons.${personId[0]}.mobilityAssistiveDevices', isVisible: true });
    testHelpers.inputCheckboxTest({ context, path: 'household.persons.${personId[0]}.mobilityAssistiveDevices', values: ['?'] });

    // Test string widget personMobilityAssistiveDevicesSpecify with conditional personAssistiveDevicesIsOtherConditional
    /* @link file://./../src/survey/common/conditionals.tsx */
    testHelpers.inputVisibleTest({ context, path: 'household.persons.${personId[0]}.mobilityAssistiveDevicesSpecify', isVisible: true });
    testHelpers.inputStringTest({ context, path: 'household.persons.${personId[0]}.mobilityAssistiveDevicesSpecify', value: '?' });

    // Test radio widget personMostUsedMobilityAssistiveDevice with conditional mostUsedMobilityAssistiveDeviceCustomConditional with choices mostUsedMobilityAssistiveDeviceCustomChoices
    /* @link file://./../src/survey/common/conditionals.tsx */
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputVisibleTest({ context, path: 'household.persons.${personId[0]}.mostUsedMobilityAssistiveDevice', isVisible: true });
    testHelpers.inputRadioTest({ context, path: 'household.persons.${personId[0]}.mostUsedMobilityAssistiveDevice', value: '?' });

    // Test radio widget personUseParatransit with conditional hasDisabilityConditional with choices yesNoPreferNotToAnswer
    /* @link file://./../src/survey/common/conditionals.tsx */
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputVisibleTest({ context, path: 'household.persons.${personId[0]}.useParatransit', isVisible: true });
    testHelpers.inputRadioTest({ context, path: 'household.persons.${personId[0]}.useParatransit', value: '?' });

    // Test radio widget personDisabilitiesFrequenciesParatransit with conditional paratransitFrequenciesConditional with choices paratransitFrequencies
    /* @link file://./../src/survey/common/conditionals.tsx */
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputVisibleTest({ context, path: 'household.persons.${personId[0]}.disabilitiesFrequenciesParatransit', isVisible: true });
    testHelpers.inputRadioTest({ context, path: 'household.persons.${personId[0]}.disabilitiesFrequenciesParatransit', value: '?' });

    // Test radio widget personDisabilitiesFrequenciesTransit with conditional paratransitFrequenciesConditional with choices paratransitFrequenciesTransit
    /* @link file://./../src/survey/common/conditionals.tsx */
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputVisibleTest({ context, path: 'household.persons.${personId[0]}.disabilitiesFrequenciesTransit', isVisible: true });
    testHelpers.inputRadioTest({ context, path: 'household.persons.${personId[0]}.disabilitiesFrequenciesTransit', value: '?' });

    // Test radio widget personStudentType with conditional ifAge16OrMoreConditional with choices participationStatusStudent
    /* @link file://./../src/survey/common/conditionals.tsx */
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputVisibleTest({ context, path: 'household.persons.${personId[0]}.studentType', isVisible: true });
    testHelpers.inputRadioTest({ context, path: 'household.persons.${personId[0]}.studentType', value: '?' });

    // Test radio widget personWorkerType with conditional ifAge14orMoreConditional with choices participationStatusWorker
    /* @link file://./../src/survey/common/conditionals.tsx */
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputVisibleTest({ context, path: 'household.persons.${personId[0]}.workerType', isVisible: true });
    testHelpers.inputRadioTest({ context, path: 'household.persons.${personId[0]}.workerType', value: '?' });

    // Test string widget personJob with conditional isWorkerConditional
    /* @link file://./../src/survey/common/conditionals.tsx */
    testHelpers.inputVisibleTest({ context, path: 'household.persons.${personId[0]}.job', isVisible: true });
    testHelpers.inputStringTest({ context, path: 'household.persons.${personId[0]}.job', value: '?' });

    // Test radio widget personJobType with conditional isWorkerConditional with choices jobTypes
    /* @link file://./../src/survey/common/conditionals.tsx */
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputVisibleTest({ context, path: 'household.persons.${personId[0]}.jobType', isVisible: true });
    testHelpers.inputRadioTest({ context, path: 'household.persons.${personId[0]}.jobType', value: '?' });

    // Test radio widget personWorkPlaceType with conditional isWorkerConditional with choices workPlaceTypeChoices
    /* @link file://./../src/survey/common/conditionals.tsx */
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputVisibleTest({ context, path: 'household.persons.${personId[0]}.workPlaceType', isVisible: true });
    testHelpers.inputRadioTest({ context, path: 'household.persons.${personId[0]}.workPlaceType', value: '?' });

    // Test radionumber widget personWorkDays with conditional personWorkDaysConditional
    /* @link file://./../src/survey/common/conditionals.tsx */
    testHelpers.inputVisibleTest({ context, path: 'household.persons.${personId[0]}.workDays', isVisible: true });

    // Test custom widget personTravelToWorkDays with conditional personWorkTripDaysConditional
    /* @link file://./../src/survey/common/conditionals.tsx */
    testHelpers.inputVisibleTest({ context, path: 'household.persons.${personId[0]}.travelToWorkDays', isVisible: true });
    // Implement custom test

    // Test radio widget personOccupation with conditional personOccupationCustomConditional with choices personOccupation
    /* @link file://./../src/survey/common/conditionals.tsx */
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputVisibleTest({ context, path: 'household.persons.${personId[0]}.occupation', isVisible: true });
    testHelpers.inputRadioTest({ context, path: 'household.persons.${personId[0]}.occupation', value: '?' });

    // Test radio widget personEducationalAttainment with conditional educationalAttainmentConditional with choices educationalAttainment
    /* @link file://./../src/survey/common/conditionals.tsx */
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputVisibleTest({ context, path: 'household.persons.${personId[0]}.educationalAttainment', isVisible: true });
    testHelpers.inputRadioTest({ context, path: 'household.persons.${personId[0]}.educationalAttainment', value: '?' });

    // Test nextbutton widget household_save
    testHelpers.inputNextButtonTest({ context, text: '?', nextPageUrl: '?' });

    // Verify the household navigation is completed
    testHelpers.verifyNavBarButtonStatus({ context, buttonText: 'household', buttonStatus: 'completed', isDisabled: false });
};

/********** Tests Selectperson section **********/
export const fillSelectpersonSectionTests = ({ context, householdSize }: CommonTestParametersModify) => {
    // Verify the selectPerson navigation is active
    testHelpers.verifyNavBarButtonStatus({ context, buttonText: 'selectPerson', buttonStatus: 'active', isDisabled: false });

    // Progress bar test for selectPerson section
    testHelpers.sectionProgressBarTest({ context, sectionName: 'selectPerson', completionPercentage: 0 });

    // Test custom widget selectPerson
    // Implement custom test

    // Test nextbutton widget buttonSelectPersonConfirm
    testHelpers.inputNextButtonTest({ context, text: '?', nextPageUrl: '?' });

    // Verify the selectPerson navigation is completed
    testHelpers.verifyNavBarButtonStatus({ context, buttonText: 'selectPerson', buttonStatus: 'completed', isDisabled: false });
};

/********** Tests Tripsintro section **********/
export const fillTripsintroSectionTests = ({ context, householdSize }: CommonTestParametersModify) => {
    // Verify the tripsIntro navigation is active
    testHelpers.verifyNavBarButtonStatus({ context, buttonText: 'tripsIntro', buttonStatus: 'active', isDisabled: false });

    // Progress bar test for tripsIntro section
    testHelpers.sectionProgressBarTest({ context, sectionName: 'tripsIntro', completionPercentage: 0 });

    // Test builtin widget activePersonTitle with conditional hasHouseholdSize2OrMoreConditional
    /* @link file://./../src/survey/common/conditionals.tsx */
    testHelpers.inputVisibleTest({ context, path: 'activePersonTitle', isVisible: true });

    // Test builtin widget buttonSwitchPerson

    // Test custom widget personNewPerson
    // Implement custom test

    // Test radio widget personWhoWillAnswerForThisPerson with conditional if2OrMorePersons14OrMoreYearsOldCustomConditional with choices whoAnswersCustomChoices
    /* @link file://./../src/survey/common/conditionals.tsx */
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputVisibleTest({ context, path: 'household.persons.{_activePersonId}.whoWillAnswerForThisPerson', isVisible: true });
    testHelpers.inputRadioTest({ context, path: 'household.persons.{_activePersonId}.whoWillAnswerForThisPerson', value: '?' });

    // Test radio widget personDidTrips with choices yesNo
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputRadioTest({ context, path: 'household.persons.{_activePersonId}.journeys.{_activeJourneyId}.personDidTrips', value: '?' });

    // Test radio widget personDidTripsConfirm with conditional personDeclaredTripsCustomConditional with choices personDidTripsConfirmCustomChoices
    /* @link file://./../src/survey/common/conditionals.tsx */
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputVisibleTest({ context, path: 'household.persons.{_activePersonId}.journeys.{_activeJourneyId}.personDidTripsConfirm', isVisible: true });
    testHelpers.inputRadioTest({ context, path: 'household.persons.{_activePersonId}.journeys.{_activeJourneyId}.personDidTripsConfirm', value: '?' });

    // Test infotext widget visitedPlacesIntro with conditional personDidTripsConditional
    /* @link file://./../src/survey/common/conditionals.tsx */
    testHelpers.inputVisibleTest({ context, path: 'household.persons.{_activePersonId}.journeys.{_activeJourneyId}.visitedPlacesIntro', isVisible: true });
    testHelpers.waitTextVisible({ context, text: '?' });

    // Test radio widget personDeparturePlaceIsHome with conditional personDidTripsAndDeparturePlaceNotSetCustomConditional with choices yesNo
    /* @link file://./../src/survey/common/conditionals.tsx */
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputVisibleTest({ context, path: 'household.persons.{_activePersonId}.journeys.{_activeJourneyId}.departurePlaceIsHome', isVisible: true });
    testHelpers.inputRadioTest({ context, path: 'household.persons.{_activePersonId}.journeys.{_activeJourneyId}.departurePlaceIsHome', value: '?' });

    // Test radio widget personDeparturePlaceOther with conditional departurePlaceOtherCustomConditional with choices departurePlaceOtherChoices
    /* @link file://./../src/survey/common/conditionals.tsx */
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputVisibleTest({ context, path: 'household.persons.{_activePersonId}.journeys.{_activeJourneyId}.departurePlaceOther', isVisible: true });
    testHelpers.inputRadioTest({ context, path: 'household.persons.{_activePersonId}.journeys.{_activeJourneyId}.departurePlaceOther', value: '?' });

    // Test radio widget personReturnedHome with conditional returnedHomeConditional with choices returnedHomeCustomChoices
    /* @link file://./../src/survey/common/conditionals.tsx */
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputVisibleTest({ context, path: 'household.persons.{_activePersonId}.journeys.{_activeJourneyId}.returnedHome', isVisible: true });
    testHelpers.inputRadioTest({ context, path: 'household.persons.{_activePersonId}.journeys.{_activeJourneyId}.returnedHome', value: '?' });

    // Test checkbox widget personOutOfTerritoryMembers with conditional outOfTerritoryMembersConditional with choices outOfTerritoryMembersCustomChoices
    /* @link file://./../src/survey/common/conditionals.tsx */
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputVisibleTest({ context, path: 'household.persons.{_activePersonId}.journeys.{_activeJourneyId}.outOfTerritoryMembers', isVisible: true });
    testHelpers.inputCheckboxTest({ context, path: 'household.persons.{_activePersonId}.journeys.{_activeJourneyId}.outOfTerritoryMembers', values: ['?'] });

    // Test nextbutton widget tripsIntro_save
    testHelpers.inputNextButtonTest({ context, text: '?', nextPageUrl: '?' });

    // Verify the tripsIntro navigation is completed
    testHelpers.verifyNavBarButtonStatus({ context, buttonText: 'tripsIntro', buttonStatus: 'completed', isDisabled: false });

    // Test infotext widget tripsIntroOutro
    testHelpers.waitTextVisible({ context, text: '?' });
};

/********** Tests Visitedplaces section **********/
export const fillVisitedplacesSectionTests = ({ context, householdSize }: CommonTestParametersModify) => {
    // Verify the visitedPlaces navigation is active
    testHelpers.verifyNavBarButtonStatus({ context, buttonText: 'visitedPlaces', buttonStatus: 'active', isDisabled: false });

    // Progress bar test for visitedPlaces section
    testHelpers.sectionProgressBarTest({ context, sectionName: 'visitedPlaces', completionPercentage: 0 });

    // Test builtin widget activePersonTitle with conditional hasHouseholdSize2OrMoreConditional
    /* @link file://./../src/survey/common/conditionals.tsx */
    testHelpers.inputVisibleTest({ context, path: 'activePersonTitle', isVisible: true });

    // Test builtin widget buttonSwitchPerson

    // Test builtin widget personVisitedPlacesTitle

    // Test builtin widget personVisitedPlacesMap

    // Test builtin widget personVisitedPlaces

    // Test builtin widget visitedPlaceActivityCategory

    // Test builtin widget visitedPlaceActivity

    // Test builtin widget visitedPlaceOnTheRoadPreviousPlaceActivity

    // Test builtin widget visitedPlacePreviousWorkPlaceName

    // Test builtin widget visitedPlacePreviousWorkPlaceGeography

    // Test builtin widget visitedPlaceAlreadyVisited with conditional alreadyVisitedPlaceCustomConditional with choices yesNo
    /* @link file://./../src/survey/common/conditionals.tsx */
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputVisibleTest({ context, path: '?.alreadyVisitedBySelfOrAnotherHouseholdMember', isVisible: true });

    // Test builtin widget visitedPlaceShortcut

    // Test builtin widget visitedPlaceName

    // Test builtin widget visitedPlaceGeography

    // Test builtin widget visitedPlacePreviousPreviousDepartureTime

    // Test builtin widget visitedPlacePreviousArrivalTime

    // Test builtin widget visitedPlacePreviousDepartureTime

    // Test builtin widget visitedPlaceArrivalTime

    // Test builtin widget visitedPlaceNextPlaceCategory

    // Test builtin widget visitedPlaceOnTheRoadNextPlaceCategory

    // Test builtin widget visitedPlaceDepartureTime

    // Test builtin widget buttonSaveVisitedPlace

    // Test builtin widget buttonCancelVisitedPlace

    // Test builtin widget buttonDeleteVisitedPlace

    // Test builtin widget buttonVisitedPlacesConfirmNextSection with conditional lastPlaceEnteredCustomConditional
    /* @link file://./../src/survey/common/conditionals.tsx */
    testHelpers.inputVisibleTest({ context, path: 'visitedPlaces.save', isVisible: true });
};

/********** Tests Segments section **********/
export const fillSegmentsSectionTests = ({ context, householdSize }: CommonTestParametersModify) => {
    // Verify the segments navigation is active
    testHelpers.verifyNavBarButtonStatus({ context, buttonText: 'segments', buttonStatus: 'active', isDisabled: false });

    // Progress bar test for segments section
    testHelpers.sectionProgressBarTest({ context, sectionName: 'segments', completionPercentage: 0 });

    // Test builtin widget activePersonTitle

    // Test builtin widget buttonSwitchPerson

    // Test builtin widget personTripsTitle

    // Test builtin widget personVisitedPlacesMap

    // Test builtin widget personTrips

    // Test builtin widget segmentIntro

    // Test builtin widget segments

    // Test builtin widget segmentSameModeAsReverseTrip

    // Test builtin widget segmentModePre

    // Test builtin widget segmentMode

    // Test radio widget segmentPaidForParking with conditional isCarDriverAndShouldShowPaidParkingCustomConditional with choices paidForParkingChoices
    /* @link file://./../src/survey/common/conditionals.tsx */
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputVisibleTest({ context, path: '?.paidForParking', isVisible: true });
    testHelpers.inputRadioTest({ context, path: '?.paidForParking', value: '?' });

    // Test radionumber widget segmentVehicleOccupancy with conditional isSelfDeclaredCarDriverCustomConditional
    /* @link file://./../src/survey/common/conditionals.tsx */
    testHelpers.inputVisibleTest({ context, path: '?.vehicleOccupancy', isVisible: true });

    // Test builtin widget segmentDriver

    // Test custom widget segmentSubwayStationStart with conditional subwayConditional
    /* @link file://./../src/survey/common/conditionals.tsx */
    testHelpers.inputVisibleTest({ context, path: '?.subwayStationStart', isVisible: true });
    // Implement custom test

    // Test custom widget segmentSubwayStationEnd with conditional subwayConditional
    /* @link file://./../src/survey/common/conditionals.tsx */
    testHelpers.inputVisibleTest({ context, path: '?.subwayStationEnd', isVisible: true });
    // Implement custom test

    // Test radio widget segmentSubwayStationsTransfer with conditional subwayTransferCustomConditional with choices subwayStationsTransferCustomChoices
    /* @link file://./../src/survey/common/conditionals.tsx */
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputVisibleTest({ context, path: '?.subwayStationsTransfer', isVisible: true });
    testHelpers.inputRadioTest({ context, path: '?.subwayStationsTransfer', value: '?' });

    // Test radio widget segmentSubwayLine with conditional subwayLineConditional with choices subwayLineChoices
    /* @link file://./../src/survey/common/conditionals.tsx */
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputVisibleTest({ context, path: '?.subwayLine', isVisible: true });
    testHelpers.inputRadioTest({ context, path: '?.subwayLine', value: '?' });

    // Test custom widget segmentTrainStationStart with conditional trainConditional
    /* @link file://./../src/survey/common/conditionals.tsx */
    testHelpers.inputVisibleTest({ context, path: '?.trainStationStart', isVisible: true });
    // Implement custom test

    // Test custom widget segmentTrainStationEnd with conditional trainConditional
    /* @link file://./../src/survey/common/conditionals.tsx */
    testHelpers.inputVisibleTest({ context, path: '?.trainStationEnd', isVisible: true });
    // Implement custom test

    // Test custom widget segmentRemStationStart with conditional remConditional
    /* @link file://./../src/survey/common/conditionals.tsx */
    testHelpers.inputVisibleTest({ context, path: '?.remStationStart', isVisible: true });
    // Implement custom test

    // Test custom widget segmentRemStationEnd with conditional remConditional
    /* @link file://./../src/survey/common/conditionals.tsx */
    testHelpers.inputVisibleTest({ context, path: '?.remStationEnd', isVisible: true });
    // Implement custom test

    // Test radio widget segmentPlaneStationStart with conditional isPlaneAndSegmentOriginInTerritoryCustomConditional with choices planeStationChoices
    /* @link file://./../src/survey/common/conditionals.tsx */
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputVisibleTest({ context, path: '?.planeStationStart', isVisible: true });
    testHelpers.inputRadioTest({ context, path: '?.planeStationStart', value: '?' });

    // Test radio widget segmentIntercityRailStationStart with conditional isIntercityRailAndSegmentOriginInTerritoryCustomConditional with choices intercityRailStationChoices
    /* @link file://./../src/survey/common/conditionals.tsx */
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputVisibleTest({ context, path: '?.intercityRailStationStart', isVisible: true });
    testHelpers.inputRadioTest({ context, path: '?.intercityRailStationStart', value: '?' });

    // Test radio widget segmentIntercityBusStationStart with conditional isIntercityBusAndSegmentOriginInTerritoryCustomConditional with choices intercityBusStationChoices
    /* @link file://./../src/survey/common/conditionals.tsx */
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputVisibleTest({ context, path: '?.intercityBusStationStart', isVisible: true });
    testHelpers.inputRadioTest({ context, path: '?.intercityBusStationStart', value: '?' });

    // Test radio widget segmentPlaneStationEnd with conditional isPlaneAndSegmentDestinationInTerritoryCustomConditional with choices planeStationChoices
    /* @link file://./../src/survey/common/conditionals.tsx */
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputVisibleTest({ context, path: '?.planeStationEnd', isVisible: true });
    testHelpers.inputRadioTest({ context, path: '?.planeStationEnd', value: '?' });

    // Test radio widget segmentIntercityRailStationEnd with conditional isIntercityRailAndSegmentDestinationInTerritoryCustomConditional with choices intercityRailStationChoices
    /* @link file://./../src/survey/common/conditionals.tsx */
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputVisibleTest({ context, path: '?.intercityRailStationEnd', isVisible: true });
    testHelpers.inputRadioTest({ context, path: '?.intercityRailStationEnd', value: '?' });

    // Test radio widget segmentIntercityBusStationEnd with conditional isIntercityBusAndSegmentDestinationInTerritoryCustomConditional with choices intercityBusStationChoices
    /* @link file://./../src/survey/common/conditionals.tsx */
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputVisibleTest({ context, path: '?.intercityBusStationEnd', isVisible: true });
    testHelpers.inputRadioTest({ context, path: '?.intercityBusStationEnd', value: '?' });

    // Test custom widget segmentBusLines with conditional busConditional
    /* @link file://./../src/survey/common/conditionals.tsx */
    testHelpers.inputVisibleTest({ context, path: '?.busLines', isVisible: true });
    // Implement custom test

    // Test custom widget segmentBusLinesWarning
    // Widget not active

    // Test radio widget segmentTransitAccessMode with conditional isTransitModeAndDistanceFromOriginCustomConditional with choices transitModesChoices
    /* @link file://./../src/survey/common/conditionals.tsx */
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputVisibleTest({ context, path: '?.transitAccessMode', isVisible: true });
    testHelpers.inputRadioTest({ context, path: '?.transitAccessMode', value: '?' });

    // Test radio widget segmentIntercityAccessMode with conditional isIntercityAndOriginInTerritoryCustomConditional with choices intercityModesChoices
    /* @link file://./../src/survey/common/conditionals.tsx */
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputVisibleTest({ context, path: '?.intercityAccessMode', isVisible: true });
    testHelpers.inputRadioTest({ context, path: '?.intercityAccessMode', value: '?' });

    // Test radio widget segmentTransitEgressMode with conditional isTransitModeAndDistanceToDestinationCustomConditional with choices transitModesChoices
    /* @link file://./../src/survey/common/conditionals.tsx */
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputVisibleTest({ context, path: '?.transitEgressMode', isVisible: true });
    testHelpers.inputRadioTest({ context, path: '?.transitEgressMode', value: '?' });

    // Test radio widget segmentIntercityEgressMode with conditional isIntercityAndDestinationInTerritoryCustomConditional with choices intercityModesChoices
    /* @link file://./../src/survey/common/conditionals.tsx */
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputVisibleTest({ context, path: '?.intercityEgressMode', isVisible: true });
    testHelpers.inputRadioTest({ context, path: '?.intercityEgressMode', value: '?' });

    // Test select widget tripJunctionPrivateBus with conditional junctionPrivateBusCustomConditional with choices tripJunctionCustomChoices
    /* @link file://./../src/survey/common/conditionals.tsx */
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputVisibleTest({ context, path: '?.junctionPrivateBus', isVisible: true });

    // Test select widget tripJunctionBusPrivate with conditional junctionBusPrivateCustomConditional with choices tripJunctionCustomChoices
    /* @link file://./../src/survey/common/conditionals.tsx */
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputVisibleTest({ context, path: '?.junctionBusPrivate', isVisible: true });

    // Test radio widget tripJunctionPaidParking with conditional junctionPaidParkingCustomConditional with choices paidForParkingChoices
    /* @link file://./../src/survey/common/conditionals.tsx */
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputVisibleTest({ context, path: '?.junctionPointPaidParking', isVisible: true });
    testHelpers.inputRadioTest({ context, path: '?.junctionPointPaidParking', value: '?' });

    // Test builtin widget segmentHasNextMode

    // Test checkbox widget personTripsCommonTripWith with conditional commonTripCustomConditional with choices commonTripCustomChoices
    /* @link file://./../src/survey/common/conditionals.tsx */
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputVisibleTest({ context, path: '?.commonTripWith', isVisible: true });
    testHelpers.inputCheckboxTest({ context, path: '?.commonTripWith', values: ['?'] });

    // Test builtin widget buttonSaveTrip

    // Test builtin widget buttonConfirmNextSection with conditional lastPlaceEnteredCustomConditional
    /* @link file://./../src/survey/common/conditionals.tsx */
    testHelpers.inputVisibleTest({ context, path: 'segments.save', isVisible: true });
};

/********** Tests Travelbehavior section **********/
export const fillTravelbehaviorSectionTests = ({ context, householdSize }: CommonTestParametersModify) => {
    // Verify the travelBehavior navigation is active
    testHelpers.verifyNavBarButtonStatus({ context, buttonText: 'travelBehavior', buttonStatus: 'active', isDisabled: false });

    // Progress bar test for travelBehavior section
    testHelpers.sectionProgressBarTest({ context, sectionName: 'travelBehavior', completionPercentage: 0 });

    // Test builtin widget activePersonTitle

    // Test builtin widget buttonSwitchPerson

    // Test infotext widget personNoWorkTripIntro with conditional shouldAskForNoWorkTripReasonCustomConditional
    /* @link file://./../src/survey/common/conditionals.tsx */
    testHelpers.inputVisibleTest({ context, path: 'household.persons.{_activePersonId}.journeys.{_activeJourneyId}.personNoWorkTripIntro', isVisible: true });
    testHelpers.waitTextVisible({ context, text: '?' });

    // Test select widget personNoWorkTripReason with conditional shouldAskForNoWorkTripReasonCustomConditional with choices noWorkTripReasonChoices
    /* @link file://./../src/survey/common/conditionals.tsx */
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputVisibleTest({ context, path: 'household.persons.{_activePersonId}.journeys.{_activeJourneyId}.noWorkTripReason', isVisible: true });

    // Test infotext widget personUsualWorkPlaceIntro with conditional hasWorkingLocationNotSetCustomConditional
    /* @link file://./../src/survey/common/conditionals.tsx */
    testHelpers.inputVisibleTest({ context, path: 'household.persons.{_activePersonId}.journeys.{_activeJourneyId}.usualWorkPlaceIntro', isVisible: true });
    testHelpers.waitTextVisible({ context, text: '?' });

    // Test string widget personUsualWorkPlaceName with conditional hasWorkingLocationNotSetCustomConditional
    /* @link file://./../src/survey/common/conditionals.tsx */
    testHelpers.inputVisibleTest({ context, path: 'household.persons.{_activePersonId}.usualWorkPlace.name', isVisible: true });
    testHelpers.inputStringTest({ context, path: 'household.persons.{_activePersonId}.usualWorkPlace.name', value: '?' });

    // Test custom widget personUsualWorkPlaceGeography with conditional hasWorkingLocationNotSetCustomConditional
    /* @link file://./../src/survey/common/conditionals.tsx */
    testHelpers.inputVisibleTest({ context, path: 'household.persons.{_activePersonId}.usualWorkPlace.geography', isVisible: true });
    // Implement custom test

    // Test radio widget personUsualWorkPlaceCommuting with conditional hasWorkingLocationNotSetCustomConditional with choices usualWorkPlaceCommutingModes
    /* @link file://./../src/survey/common/conditionals.tsx */
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputVisibleTest({ context, path: 'household.persons.{_activePersonId}.usualWorkPlaceCommuting', isVisible: true });
    testHelpers.inputRadioTest({ context, path: 'household.persons.{_activePersonId}.usualWorkPlaceCommuting', value: '?' });

    // Test infotext widget personNoSchoolTripIntro with conditional shouldAskForNoSchoolTripFollowupCustomConditional
    /* @link file://./../src/survey/common/conditionals.tsx */
    testHelpers.inputVisibleTest({ context, path: 'household.persons.{_activePersonId}.journeys.{_activeJourneyId}.personNoSchoolTripIntro', isVisible: true });
    testHelpers.waitTextVisible({ context, text: '?' });

    // Test radio widget personHasSchoolPlace with conditional shouldAskForNoSchoolTripFollowupCustomConditional with choices yesNo
    /* @link file://./../src/survey/common/conditionals.tsx */
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputVisibleTest({ context, path: 'household.persons.{_activePersonId}.hasSchoolPlace', isVisible: true });
    testHelpers.inputRadioTest({ context, path: 'household.persons.{_activePersonId}.hasSchoolPlace', value: '?' });

    // Test string widget personUsualSchoolPlaceName with conditional hasSchoolLocationNotSetConditional
    /* @link file://./../src/survey/common/conditionals.tsx */
    testHelpers.inputVisibleTest({ context, path: 'household.persons.{_activePersonId}.usualSchoolPlace.name', isVisible: true });
    testHelpers.inputStringTest({ context, path: 'household.persons.{_activePersonId}.usualSchoolPlace.name', value: '?' });

    // Test custom widget personUsualSchoolPlaceGeography with conditional hasSchoolLocationNotSetConditional
    /* @link file://./../src/survey/common/conditionals.tsx */
    testHelpers.inputVisibleTest({ context, path: 'household.persons.{_activePersonId}.usualSchoolPlace.geography', isVisible: true });
    // Implement custom test

    // Test select widget personNoSchoolTripReason with conditional hasSchoolLocationNotSetConditional with choices noSchoolTripReasonChoices
    /* @link file://./../src/survey/common/conditionals.tsx */
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputVisibleTest({ context, path: 'household.persons.{_activePersonId}.journeys.{_activeJourneyId}.noSchoolTripReason', isVisible: true });

    // Test nextbutton widget buttonTravelBehaviorConfirmNextSection
    testHelpers.inputNextButtonTest({ context, text: '?', nextPageUrl: '?' });

    // Verify the travelBehavior navigation is completed
    testHelpers.verifyNavBarButtonStatus({ context, buttonText: 'travelBehavior', buttonStatus: 'completed', isDisabled: false });
};

/********** Tests Omissions section **********/
export const fillOmissionsSectionTests = ({ context, householdSize }: CommonTestParametersModify) => {
    // Verify the omissions navigation is active
    testHelpers.verifyNavBarButtonStatus({ context, buttonText: 'omissions', buttonStatus: 'active', isDisabled: false });

    // Progress bar test for omissions section
    testHelpers.sectionProgressBarTest({ context, sectionName: 'omissions', completionPercentage: 0 });

    // Test radio widget toddlerDaycare with conditional toddlerDaycareCustomConditional with choices yesNo
    /* @link file://./../src/survey/common/conditionals.tsx */
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputVisibleTest({ context, path: 'omissions.toddlerDaycare', isVisible: true });
    testHelpers.inputRadioTest({ context, path: 'omissions.toddlerDaycare', value: '?' });

    // Test checkbox widget toddlerDaycareDropoff with conditional toddlerDaycareConditional with choices person14PlusAndOtherCustomChoices
    /* @link file://./../src/survey/common/conditionals.tsx */
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputVisibleTest({ context, path: 'omissions.toddlerDaycareDropoff', isVisible: true });
    testHelpers.inputCheckboxTest({ context, path: 'omissions.toddlerDaycareDropoff', values: ['?'] });

    // Test radio widget toddlerDaycareDropoffMode with conditional toddlerDaycareConditional with choices toddlerDaycareMode
    /* @link file://./../src/survey/common/conditionals.tsx */
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputVisibleTest({ context, path: 'omissions.toddlerDaycareDropoffMode', isVisible: true });
    testHelpers.inputRadioTest({ context, path: 'omissions.toddlerDaycareDropoffMode', value: '?' });

    // Test checkbox widget toddlerDaycarePickup with conditional toddlerDaycareConditional with choices person14PlusAndOtherCustomChoices
    /* @link file://./../src/survey/common/conditionals.tsx */
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputVisibleTest({ context, path: 'omissions.toddlerDaycarePickup', isVisible: true });
    testHelpers.inputCheckboxTest({ context, path: 'omissions.toddlerDaycarePickup', values: ['?'] });

    // Test radio widget toddlerDaycarePickupMode with conditional toddlerDaycareConditional with choices toddlerDaycareMode
    /* @link file://./../src/survey/common/conditionals.tsx */
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputVisibleTest({ context, path: 'omissions.toddlerDaycarePickupMode', isVisible: true });
    testHelpers.inputRadioTest({ context, path: 'omissions.toddlerDaycarePickupMode', value: '?' });

    // Test radio widget hasOmittedTrips with conditional hasOmittedTripsConditional with choices yesNo
    /* @link file://./../src/survey/common/conditionals.tsx */
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputVisibleTest({ context, path: 'omissions.hasOmittedTrips', isVisible: true });
    testHelpers.inputRadioTest({ context, path: 'omissions.hasOmittedTrips', value: '?' });

    // Test infotext widget hasOmittedTripsIntro with conditional hasOmittedTripsSpecifyConditional
    /* @link file://./../src/survey/common/conditionals.tsx */
    testHelpers.inputVisibleTest({ context, path: 'omissions.hasOmittedTripsIntro', isVisible: true });
    testHelpers.waitTextVisible({ context, text: '?' });

    // Test checkbox widget hasOmittedTripsActivity with conditional hasOmittedTripsSpecifyConditional with choices hasOmittedTripsActivities
    /* @link file://./../src/survey/common/conditionals.tsx */
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputVisibleTest({ context, path: 'omissions.hasOmittedTripsActivity', isVisible: true });
    testHelpers.inputCheckboxTest({ context, path: 'omissions.hasOmittedTripsActivity', values: ['?'] });

    // Test checkbox widget hasOmittedTripsMode with conditional hasOmittedTripsSpecifyConditional with choices hasOmittedTripsModes
    /* @link file://./../src/survey/common/conditionals.tsx */
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputVisibleTest({ context, path: 'omissions.hasOmittedTripsMode', isVisible: true });
    testHelpers.inputCheckboxTest({ context, path: 'omissions.hasOmittedTripsMode', values: ['?'] });

    // Test nextbutton widget buttonCompleteOmissionsSection
    testHelpers.inputNextButtonTest({ context, text: '?', nextPageUrl: '?' });

    // Verify the omissions navigation is completed
    testHelpers.verifyNavBarButtonStatus({ context, buttonText: 'omissions', buttonStatus: 'completed', isDisabled: false });
};

/********** Tests Longdistance section **********/
export const fillLongdistanceSectionTests = ({ context, householdSize }: CommonTestParametersModify) => {
    // Verify the longDistance navigation is active
    testHelpers.verifyNavBarButtonStatus({ context, buttonText: 'longDistance', buttonStatus: 'active', isDisabled: false });

    // Progress bar test for longDistance section
    testHelpers.sectionProgressBarTest({ context, sectionName: 'longDistance', completionPercentage: 0 });

    // Test radio widget householdMadeLongDistanceTripsInLastYear with choices yesNoDontKnow
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputRadioTest({ context, path: 'household.madeLongDistanceTripsInLastYear', value: '?' });

    // Test custom widget householdLongDistanceIntroMap
    // Implement custom test

    // Test radio widget householdLongDistanceTripsMayAugust with conditional madeLongDistanceTripsConditional with choices longDistanceFrequencyChoices
    /* @link file://./../src/survey/common/conditionals.tsx */
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputVisibleTest({ context, path: 'household.longDistanceTripsMayAugust', isVisible: true });
    testHelpers.inputRadioTest({ context, path: 'household.longDistanceTripsMayAugust', value: '?' });

    // Test radio widget householdLongDistanceTripsJanuaryApril with conditional madeLongDistanceTripsConditional with choices longDistanceFrequencyChoices
    /* @link file://./../src/survey/common/conditionals.tsx */
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputVisibleTest({ context, path: 'household.longDistanceTripsJanuaryApril', isVisible: true });
    testHelpers.inputRadioTest({ context, path: 'household.longDistanceTripsJanuaryApril', value: '?' });

    // Test radio widget householdLongDistanceTripsSeptemberDecember with conditional madeLongDistanceTripsConditional with choices longDistanceFrequencyChoices
    /* @link file://./../src/survey/common/conditionals.tsx */
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputVisibleTest({ context, path: 'household.longDistanceTripsSeptemberDecember', isVisible: true });
    testHelpers.inputRadioTest({ context, path: 'household.longDistanceTripsSeptemberDecember', value: '?' });

    // Test radio widget wouldLikeToParticipateToLongDistanceSurvey with conditional madeLongDistanceTripsConditional with choices yesNo
    /* @link file://./../src/survey/common/conditionals.tsx */
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputVisibleTest({ context, path: 'household.wouldLikeToParticipateToLongDistanceSurvey', isVisible: true });
    testHelpers.inputRadioTest({ context, path: 'household.wouldLikeToParticipateToLongDistanceSurvey', value: '?' });

    // Test string widget wouldLikeToParticipateToLongDistanceSurveyContactEmail with conditional wantToParticipateInLongDistanceSurveyConditional
    /* @link file://./../src/survey/common/conditionals.tsx */
    testHelpers.inputVisibleTest({ context, path: 'household.wouldLikeToParticipateToLongDistanceSurveyContactEmail', isVisible: true });
    testHelpers.inputStringTest({ context, path: 'household.wouldLikeToParticipateToLongDistanceSurveyContactEmail', value: '?' });

    // Test nextbutton widget buttonCompleteLongDistanceSection
    testHelpers.inputNextButtonTest({ context, text: '?', nextPageUrl: '?' });

    // Verify the longDistance navigation is completed
    testHelpers.verifyNavBarButtonStatus({ context, buttonText: 'longDistance', buttonStatus: 'completed', isDisabled: false });
};

/********** Tests Barriersdisability section **********/
export const fillBarriersdisabilitySectionTests = ({ context, householdSize }: CommonTestParametersModify) => {
    // Verify the barriersDisability navigation is active
    testHelpers.verifyNavBarButtonStatus({ context, buttonText: 'barriersDisability', buttonStatus: 'active', isDisabled: false });

    // Progress bar test for barriersDisability section
    testHelpers.sectionProgressBarTest({ context, sectionName: 'barriersDisability', completionPercentage: 0 });

    // Test infotext widget barriersDisabilitySectionIntro
    testHelpers.waitTextVisible({ context, text: '?' });

    // Test infotext widget barriersDisabilitySectionIntro2 with conditional hasMoreThanOneSelfRespondentCustomConditional
    /* @link file://./../src/survey/common/conditionals.tsx */
    testHelpers.inputVisibleTest({ context, path: 'barriersDisabilitySectionIntro2', isVisible: true });
    testHelpers.waitTextVisible({ context, text: '?' });

    // Test radio widget barriersDisabilityIsPersonAvailable with conditional hasMoreThanOneSelfRespondentDefaultYesCustomConditional with choices yesNo
    /* @link file://./../src/survey/common/conditionals.tsx */
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputVisibleTest({ context, path: 'barriersDisabilityIsPersonAvailable', isVisible: true });
    testHelpers.inputRadioTest({ context, path: 'barriersDisabilityIsPersonAvailable', value: '?' });

    // Test infotext widget barriersDisabilityTrip with conditional isBarriersDisabilityTripPersonAvailableConditional
    /* @link file://./../src/survey/common/conditionals.tsx */
    testHelpers.inputVisibleTest({ context, path: 'barriersDisabilityTrip', isVisible: true });
    testHelpers.waitTextVisible({ context, text: '?' });

    // Test infotext widget barriersDisabilityIntro with conditional isBarriersDisabilityTripPersonAvailableConditional
    /* @link file://./../src/survey/common/conditionals.tsx */
    testHelpers.inputVisibleTest({ context, path: 'barriersDisabilityIntro', isVisible: true });
    testHelpers.waitTextVisible({ context, text: '?' });

    // Test radio widget barriersDisabilityFrequency with conditional isBarriersDisabilityTripPersonAvailableConditional with choices barriersChoices
    /* @link file://./../src/survey/common/conditionals.tsx */
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputVisibleTest({ context, path: 'barriersDisabilityFrequency', isVisible: true });
    testHelpers.inputRadioTest({ context, path: 'barriersDisabilityFrequency', value: '?' });

    // Test radio widget barriersDisabilityReliability with conditional isBarriersDisabilityTripPersonAvailableConditional with choices barriersChoices
    /* @link file://./../src/survey/common/conditionals.tsx */
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputVisibleTest({ context, path: 'barriersDisabilityReliability', isVisible: true });
    testHelpers.inputRadioTest({ context, path: 'barriersDisabilityReliability', value: '?' });

    // Test radio widget barriersDisabilityWalk with conditional isBarriersDisabilityTripPersonAvailableConditional with choices barriersChoices
    /* @link file://./../src/survey/common/conditionals.tsx */
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputVisibleTest({ context, path: 'barriersDisabilityWalk', isVisible: true });
    testHelpers.inputRadioTest({ context, path: 'barriersDisabilityWalk', value: '?' });

    // Test radio widget barriersDisabilityTime with conditional isBarriersDisabilityTripPersonAvailableConditional with choices barriersChoices
    /* @link file://./../src/survey/common/conditionals.tsx */
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputVisibleTest({ context, path: 'barriersDisabilityTime', isVisible: true });
    testHelpers.inputRadioTest({ context, path: 'barriersDisabilityTime', value: '?' });

    // Test radio widget barriersDisabilityTransfer with conditional isBarriersDisabilityTripPersonAvailableConditional with choices barriersChoices
    /* @link file://./../src/survey/common/conditionals.tsx */
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputVisibleTest({ context, path: 'barriersDisabilityTransfer', isVisible: true });
    testHelpers.inputRadioTest({ context, path: 'barriersDisabilityTransfer', value: '?' });

    // Test radio widget barriersDisabilitySecurity with conditional isBarriersDisabilityTripPersonAvailableConditional with choices barriersChoices
    /* @link file://./../src/survey/common/conditionals.tsx */
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputVisibleTest({ context, path: 'barriersDisabilitySecurity', isVisible: true });
    testHelpers.inputRadioTest({ context, path: 'barriersDisabilitySecurity', value: '?' });

    // Test radio widget barriersDisabilityUniversalAccessibility with conditional isBarriersDisabilityTripPersonAvailableConditional with choices barriersChoices
    /* @link file://./../src/survey/common/conditionals.tsx */
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputVisibleTest({ context, path: 'barriersDisabilityUniversalAccessibility', isVisible: true });
    testHelpers.inputRadioTest({ context, path: 'barriersDisabilityUniversalAccessibility', value: '?' });

    // Test radio widget barriersDisabilityPlanning with conditional isBarriersDisabilityTripPersonAvailableConditional with choices barriersChoices
    /* @link file://./../src/survey/common/conditionals.tsx */
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputVisibleTest({ context, path: 'barriersDisabilityPlanning', isVisible: true });
    testHelpers.inputRadioTest({ context, path: 'barriersDisabilityPlanning', value: '?' });

    // Test radio widget barriersDisabilityCourtesy with conditional isBarriersDisabilityTripPersonAvailableConditional with choices barriersChoices
    /* @link file://./../src/survey/common/conditionals.tsx */
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputVisibleTest({ context, path: 'barriersDisabilityCourtesy', isVisible: true });
    testHelpers.inputRadioTest({ context, path: 'barriersDisabilityCourtesy', value: '?' });

    // Test nextbutton widget buttonCompleteBarriersDisabilitySection
    testHelpers.inputNextButtonTest({ context, text: '?', nextPageUrl: '?' });

    // Verify the barriersDisability navigation is completed
    testHelpers.verifyNavBarButtonStatus({ context, buttonText: 'barriersDisability', buttonStatus: 'completed', isDisabled: false });
};

/********** Tests Selectfreqperson section **********/
export const fillSelectfreqpersonSectionTests = ({ context, householdSize }: CommonTestParametersModify) => {
    // Verify the selectFreqPerson navigation is active
    testHelpers.verifyNavBarButtonStatus({ context, buttonText: 'selectFreqPerson', buttonStatus: 'active', isDisabled: false });

    // Progress bar test for selectFreqPerson section
    testHelpers.sectionProgressBarTest({ context, sectionName: 'selectFreqPerson', completionPercentage: 0 });

    // Test infotext widget selectFreqPersonIntro
    testHelpers.waitTextVisible({ context, text: '?' });

    // Test radio widget selectFreqPerson with choices hhAge16PlusCustomChoices
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputRadioTest({ context, path: '_freqPersonId', value: '?' });

    // Test nextbutton widget buttonCompleteSelectFreqPersonSection
    testHelpers.inputNextButtonTest({ context, text: '?', nextPageUrl: '?' });

    // Verify the selectFreqPerson navigation is completed
    testHelpers.verifyNavBarButtonStatus({ context, buttonText: 'selectFreqPerson', buttonStatus: 'completed', isDisabled: false });
};

/********** Tests Frequencies section **********/
export const fillFrequenciesSectionTests = ({ context, householdSize }: CommonTestParametersModify) => {
    // Verify the frequencies navigation is active
    testHelpers.verifyNavBarButtonStatus({ context, buttonText: 'frequencies', buttonStatus: 'active', isDisabled: false });

    // Progress bar test for frequencies section
    testHelpers.sectionProgressBarTest({ context, sectionName: 'frequencies', completionPercentage: 0 });

    // Test infotext widget anyTripModeFrequenciesIntro
    testHelpers.waitTextVisible({ context, text: '?' });

    // Test radio widget anyTripModeFrequenciesWalk with choices anyTripModeFrequenciesChoices
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputRadioTest({ context, path: 'freqAttitudinal.anyTripModeFrequenciesWalk', value: '?' });

    // Test radio widget anyTripModeFrequenciesBicycle with choices anyTripModeFrequenciesChoices
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputRadioTest({ context, path: 'freqAttitudinal.anyTripModeFrequenciesBicycle', value: '?' });

    // Test radio widget anyTripModeFrequenciesTransit with choices anyTripModeFrequenciesChoices
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputRadioTest({ context, path: 'freqAttitudinal.anyTripModeFrequenciesTransit', value: '?' });

    // Test radio widget anyTripModeFrequenciesCarPassenger with choices anyTripModeFrequenciesChoices
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputRadioTest({ context, path: 'freqAttitudinal.anyTripModeFrequenciesCarPassenger', value: '?' });

    // Test radio widget anyTripModeFrequenciesCarDriver with conditional hasDrivingLicenseConditional with choices anyTripModeFrequenciesChoices
    /* @link file://./../src/survey/common/conditionals.tsx */
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputVisibleTest({ context, path: 'freqAttitudinal.anyTripModeFrequenciesCarDriver', isVisible: true });
    testHelpers.inputRadioTest({ context, path: 'freqAttitudinal.anyTripModeFrequenciesCarDriver', value: '?' });

    // Test nextbutton widget buttonCompleteFrequenciesSection
    testHelpers.inputNextButtonTest({ context, text: '?', nextPageUrl: '?' });

    // Verify the frequencies navigation is completed
    testHelpers.verifyNavBarButtonStatus({ context, buttonText: 'frequencies', buttonStatus: 'completed', isDisabled: false });
};

/********** Tests Attitudinal section **********/
export const fillAttitudinalSectionTests = ({ context, householdSize }: CommonTestParametersModify) => {
    // Verify the attitudinal navigation is active
    testHelpers.verifyNavBarButtonStatus({ context, buttonText: 'attitudinal', buttonStatus: 'active', isDisabled: false });

    // Progress bar test for attitudinal section
    testHelpers.sectionProgressBarTest({ context, sectionName: 'attitudinal', completionPercentage: 0 });

    // Test infotext widget attitudinalIntro
    testHelpers.waitTextVisible({ context, text: '?' });

    // Test radio widget attitudinalOpinion with choices attitudinalChoices
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputRadioTest({ context, path: 'freqAttitudinal.attitudinalOpinion', value: '?' });

    // Test radio widget attitudinalCar with choices attitudinalChoices
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputRadioTest({ context, path: 'freqAttitudinal.attitudinalCar', value: '?' });

    // Test radio widget attitudinalTransitGoodQuality with choices attitudinalChoices
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputRadioTest({ context, path: 'freqAttitudinal.attitudinalTransitGoodQuality', value: '?' });

    // Test radio widget attitudinalFamiliarWithTransit with choices attitudinalChoices
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputRadioTest({ context, path: 'freqAttitudinal.attitudinalFamiliarWithTransit', value: '?' });

    // Test radio widget attitudinalRequireHighLevel with choices attitudinalChoices
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputRadioTest({ context, path: 'freqAttitudinal.attitudinalRequireHighLevel', value: '?' });

    // Test radio widget attitudinalEasyWithoutCar with choices attitudinalChoices
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputRadioTest({ context, path: 'freqAttitudinal.attitudinalEasyWithoutCar', value: '?' });

    // Test radio widget attitudinalGoodAccessImportant with choices attitudinalChoices
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputRadioTest({ context, path: 'freqAttitudinal.attitudinalGoodAccessImportant', value: '?' });

    // Test nextbutton widget buttonCompleteAttitudinalSection
    testHelpers.inputNextButtonTest({ context, text: '?', nextPageUrl: '?' });

    // Verify the attitudinal navigation is completed
    testHelpers.verifyNavBarButtonStatus({ context, buttonText: 'attitudinal', buttonStatus: 'completed', isDisabled: false });
};

/********** Tests Barriers section **********/
export const fillBarriersSectionTests = ({ context, householdSize }: CommonTestParametersModify) => {
    // Verify the barriers navigation is active
    testHelpers.verifyNavBarButtonStatus({ context, buttonText: 'barriers', buttonStatus: 'active', isDisabled: false });

    // Progress bar test for barriers section
    testHelpers.sectionProgressBarTest({ context, sectionName: 'barriers', completionPercentage: 0 });

    // Test infotext widget barriersTrip with conditional hasBarrierTripConditional
    /* @link file://./../src/survey/common/conditionals.tsx */
    testHelpers.inputVisibleTest({ context, path: 'barriersTrip', isVisible: true });
    testHelpers.waitTextVisible({ context, text: '?' });

    // Test infotext widget barriersIntro with conditional hasBarrierTripConditional
    /* @link file://./../src/survey/common/conditionals.tsx */
    testHelpers.inputVisibleTest({ context, path: 'barriersIntro', isVisible: true });
    testHelpers.waitTextVisible({ context, text: '?' });

    // Test radio widget barriersFrequency with conditional hasBarrierTripConditional with choices barriersChoices
    /* @link file://./../src/survey/common/conditionals.tsx */
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputVisibleTest({ context, path: 'barriersFrequency', isVisible: true });
    testHelpers.inputRadioTest({ context, path: 'barriersFrequency', value: '?' });

    // Test radio widget barriersReliability with conditional hasBarrierTripConditional with choices barriersChoices
    /* @link file://./../src/survey/common/conditionals.tsx */
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputVisibleTest({ context, path: 'barriersReliability', isVisible: true });
    testHelpers.inputRadioTest({ context, path: 'barriersReliability', value: '?' });

    // Test radio widget barriersWalk with conditional hasBarrierTripConditional with choices barriersChoices
    /* @link file://./../src/survey/common/conditionals.tsx */
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputVisibleTest({ context, path: 'barriersWalk', isVisible: true });
    testHelpers.inputRadioTest({ context, path: 'barriersWalk', value: '?' });

    // Test radio widget barriersTime with conditional hasBarrierTripConditional with choices barriersChoices
    /* @link file://./../src/survey/common/conditionals.tsx */
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputVisibleTest({ context, path: 'barriersTime', isVisible: true });
    testHelpers.inputRadioTest({ context, path: 'barriersTime', value: '?' });

    // Test radio widget barriersTransfer with conditional hasBarrierTripConditional with choices barriersChoices
    /* @link file://./../src/survey/common/conditionals.tsx */
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputVisibleTest({ context, path: 'barriersTransfer', isVisible: true });
    testHelpers.inputRadioTest({ context, path: 'barriersTransfer', value: '?' });

    // Test radio widget barriersSecurity with conditional hasBarrierTripConditional with choices barriersChoices
    /* @link file://./../src/survey/common/conditionals.tsx */
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputVisibleTest({ context, path: 'barriersSecurity', isVisible: true });
    testHelpers.inputRadioTest({ context, path: 'barriersSecurity', value: '?' });

    // Test radio widget barriersPlanning with conditional hasBarrierTripConditional with choices barriersChoices
    /* @link file://./../src/survey/common/conditionals.tsx */
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputVisibleTest({ context, path: 'barriersPlanning', isVisible: true });
    testHelpers.inputRadioTest({ context, path: 'barriersPlanning', value: '?' });

    // Test nextbutton widget buttonCompleteBarriersSection
    testHelpers.inputNextButtonTest({ context, text: '?', nextPageUrl: '?' });

    // Verify the barriers navigation is completed
    testHelpers.verifyNavBarButtonStatus({ context, buttonText: 'barriers', buttonStatus: 'completed', isDisabled: false });
};

/********** Tests End section **********/
export const fillEndSectionTests = ({ context, householdSize }: CommonTestParametersModify) => {
    // Verify the end navigation is active
    testHelpers.verifyNavBarButtonStatus({ context, buttonText: 'end', buttonStatus: 'active', isDisabled: false });

    // Progress bar test for end section
    testHelpers.sectionProgressBarTest({ context, sectionName: 'end', completionPercentage: 0 });

    // Test radio widget householdType with conditional householdTypeConditional with choices householdType
    /* @link file://./../src/survey/common/conditionals.tsx */
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputVisibleTest({ context, path: 'household.type', isVisible: true });
    testHelpers.inputRadioTest({ context, path: 'household.type', value: '?' });

    // Test radio widget householdTypeSpecify with conditional householdTypeSpecifyConditional with choices householdTypeSpecify
    /* @link file://./../src/survey/common/conditionals.tsx */
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputVisibleTest({ context, path: 'household.typeSpecify', isVisible: true });
    testHelpers.inputRadioTest({ context, path: 'household.typeSpecify', value: '?' });

    // Test radionumber widget householdPluginHybridCarNumber with conditional householdHasCars
    /* @link file://./../src/survey/common/conditionals.tsx */
    testHelpers.inputVisibleTest({ context, path: 'household.pluginHybridCarNumber', isVisible: true });

    // Test radionumber widget householdElectricCarNumber with conditional householdHasCars
    /* @link file://./../src/survey/common/conditionals.tsx */
    testHelpers.inputVisibleTest({ context, path: 'household.electricCarNumber', isVisible: true });

    // Test select widget householdIncome with choices householdIncomeChoices
    /* @link file://./../src/survey/common/choices.tsx */

    // Test radio widget didRespondForCorrectAssignedDate with conditional didRespondForCorrectAssignedDateConditional with choices didRespondForCorrectAssignedDateCustomChoices
    /* @link file://./../src/survey/common/conditionals.tsx */
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputVisibleTest({ context, path: 'end.didRespondForCorrectAssignedDate', isVisible: true });
    testHelpers.inputRadioTest({ context, path: 'end.didRespondForCorrectAssignedDate', value: '?' });

    // Test checkbox widget didNotRespondForCorrectAssignedDateReasons with conditional didNotRespondForCorrectAssignedDateConditional with choices didNotRespondForCorrectAssignedDateReasons
    /* @link file://./../src/survey/common/conditionals.tsx */
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputVisibleTest({ context, path: 'end.didNotRespondForCorrectAssignedDateReasons', isVisible: true });
    testHelpers.inputCheckboxTest({ context, path: 'end.didNotRespondForCorrectAssignedDateReasons', values: ['?'] });

    // Test radio widget wouldLikeToParticipateInOtherSurveysChaireMobilite with choices yesNo
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputRadioTest({ context, path: 'end.wouldLikeToParticipateInOtherSurveysChaireMobilite', value: '?' });

    // Test string widget wouldLikeToParticipateInOtherSurveysChaireMobiliteContactEmail with conditional wantToParticipateInOtherSurveysChaireMobiliteConditional
    /* @link file://./../src/survey/common/conditionals.tsx */
    testHelpers.inputVisibleTest({ context, path: 'end.wouldLikeToParticipateInOtherSurveysChaireMobiliteContactEmail', isVisible: true });
    testHelpers.inputStringTest({ context, path: 'end.wouldLikeToParticipateInOtherSurveysChaireMobiliteContactEmail', value: '?' });

    // Test text widget householdCommentsOnSurvey
    testHelpers.inputStringTest({ context, path: 'end.commentsOnSurvey', value: '?' });

    // Test infotext widget optionalIntroText with conditional enmpConditional
    /* @link file://./../src/survey/common/conditionals.tsx */
    testHelpers.inputVisibleTest({ context, path: 'end.optionalIntroText', isVisible: true });
    testHelpers.waitTextVisible({ context, text: '?' });

    // Test range widget endInterestOfTheSurvey with conditional enmpConditional
    /* @link file://./../src/survey/common/conditionals.tsx */
    testHelpers.inputVisibleTest({ context, path: 'end.interestOfTheSurvey', isVisible: true });
    testHelpers.inputRangeTest({ context, path: 'end.interestOfTheSurvey', value: 0, sliderColor: '?' });

    // Test number widget endTimeSpentAnswering with conditional enmpConditional
    /* @link file://./../src/survey/common/conditionals.tsx */
    testHelpers.inputVisibleTest({ context, path: 'end.timeSpentAnswering', isVisible: true });
    testHelpers.inputStringTest({ context, path: 'end.timeSpentAnswering', value: '?' });

    // Test range widget endDurationOfTheSurvey with conditional enmpConditional
    /* @link file://./../src/survey/common/conditionals.tsx */
    testHelpers.inputVisibleTest({ context, path: 'end.durationOfTheSurvey', isVisible: true });
    testHelpers.inputRangeTest({ context, path: 'end.durationOfTheSurvey', value: 0, sliderColor: '?' });

    // Test range widget endDifficultyOfTheSurvey with conditional enmpConditional
    /* @link file://./../src/survey/common/conditionals.tsx */
    testHelpers.inputVisibleTest({ context, path: 'end.difficultyOfTheSurvey', isVisible: true });
    testHelpers.inputRangeTest({ context, path: 'end.difficultyOfTheSurvey', value: 0, sliderColor: '?' });

    // Test range widget endBurdenOfTheSurvey with conditional enmpConditional
    /* @link file://./../src/survey/common/conditionals.tsx */
    testHelpers.inputVisibleTest({ context, path: 'end.burdenOfTheSurvey', isVisible: true });
    testHelpers.inputRangeTest({ context, path: 'end.burdenOfTheSurvey', value: 0, sliderColor: '?' });

    // Test radio widget endConsideredAbandoningSurvey with conditional enmpConditional with choices yesNoDontKnow
    /* @link file://./../src/survey/common/conditionals.tsx */
    /* @link file://./../src/survey/common/choices.tsx */
    testHelpers.inputVisibleTest({ context, path: 'end.consideredAbandoningSurvey', isVisible: true });
    testHelpers.inputRadioTest({ context, path: 'end.consideredAbandoningSurvey', value: '?' });

    // Test nextbutton widget buttonCompleteInterviewWithCompleteSection
    testHelpers.inputNextButtonTest({ context, text: '?', nextPageUrl: '?' });

    // Verify the end navigation is completed
    testHelpers.verifyNavBarButtonStatus({ context, buttonText: 'end', buttonStatus: 'completed', isDisabled: false });
};

/********** Tests Completed section **********/
export const fillCompletedSectionTests = ({ context, householdSize }: CommonTestParametersModify) => {
    // Verify the completed navigation is active
    testHelpers.verifyNavBarButtonStatus({ context, buttonText: 'completed', buttonStatus: 'active', isDisabled: false });

    // Progress bar test for completed section
    testHelpers.sectionProgressBarTest({ context, sectionName: 'completed', completionPercentage: 0 });

    // Test infotext widget completedText
    testHelpers.waitTextVisible({ context, text: '?' });

    // Test custom widget buttonARTMPanel
    // Implement custom test

    // Test infotext widget mapARTMImage
    // Widget not active
};
