// This file was automatically generated by the Evolution Generator.
// The Evolution Generator is used to automate the creation of consistent, reliable code.
// Any changes made to this file will be overwritten.

import { isSectionCompleted } from 'evolution-common/lib/services/questionnaire/sections/navigationHelpers';
import { SectionConfig } from 'evolution-common/lib/services/questionnaire/types';
import { widgetsNames } from './widgetsNames';
import {
    hasMoreThanOneSelfRespondentOfDrivingAgeAndNoDisability,
    preEndNoDisabilityConditional,
    updateHouseholdSizeFromPersonCount
} from '../../common/customHelpers';
import { allPersonsTripDiariesCompleted } from '../../common/helper';

export const currentSectionName: string = 'selectFreqPerson';
const previousSectionName: SectionConfig['previousSection'] = 'barriersDisability';
const nextSectionName: SectionConfig['nextSection'] = 'frequencies';

const visibleEps = ['freqAttitudinal', 'freqAttitudinalBarriers', 'freqBarriers'];

// Config for the section
export const sectionConfig: SectionConfig = {
    previousSection: previousSectionName,
    nextSection: nextSectionName,
    title: {
        fr: 'Sélection du répondant aux fréquences',
        en: 'Frequencies respondent selection'
    },
    navMenu: {
        type: 'hidden',
        parentSection: 'end'
    },
    widgets: widgetsNames,
    // Do some actions before the section is loaded
    // Allow to click on the section menu
    enableConditional: function (interview) {
        // FIXME Wrong condition but it works for now. Evolution should support blocks of optional sections See https://github.com/chairemobilite/evolution/issues/1634
        return allPersonsTripDiariesCompleted(interview);
    },
    // Determine if the current section is completed
    completionConditional: function (interview) {
        // Completed if partial sample is not one of the frequencies or actually
        // completed or if the household has only one person of driving age
        return (
            !preEndNoDisabilityConditional(interview, visibleEps) ||
            !hasMoreThanOneSelfRespondentOfDrivingAgeAndNoDisability(interview) ||
            isSectionCompleted({ interview, sectionName: currentSectionName })
        );
    },
    onSectionEntry: updateHouseholdSizeFromPersonCount,
    isSectionVisible: (interview) => {
        // Section visible seulement si échantillon partiel exclusif est est
        // l'un des 3 avec freq et qu'il y a plus d'un membre correspondant aux
        // critères d'auto-répondant en âge de conduire
        return (
            preEndNoDisabilityConditional(interview, visibleEps) &&
            hasMoreThanOneSelfRespondentOfDrivingAgeAndNoDisability(interview)
        );
    }
};

export default sectionConfig;
