// This file was automatically generated by the Evolution Generator.
// The Evolution Generator is used to automate the creation of consistent, reliable code.
// Any changes made to this file will be overwritten.

import { TFunction } from 'i18next';
import * as defaultInputBase from 'evolution-frontend/lib/components/inputs/defaultInputBase';
import { defaultConditional } from 'evolution-common/lib/services/widgets/conditionals/defaultConditional';
import * as WidgetConfig from 'evolution-common/lib/services/questionnaire/types';
import * as validations from 'evolution-common/lib/services/widgets/validations/validations';
import * as customChoices from './customChoices';

export const selectFreqPersonIntro: WidgetConfig.TextWidgetConfig = {
    ...defaultInputBase.infoTextBase,
    path: 'selectFreqPersonIntro',
    containsHtml: true,
    text: (t: TFunction) => t('selectFreqPerson:selectFreqPersonIntro'),
    conditional: defaultConditional
};

export const selectFreqPerson: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: '_freqPersonId',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction) => t('selectFreqPerson:selectFreqPerson'),
    choices: customChoices.hhAge16PlusCustomChoices,
    conditional: defaultConditional,
    validations: validations.requiredValidation
};

export const buttonCompleteSelectFreqPersonSection: WidgetConfig.ButtonWidgetConfig = {
    ...defaultInputBase.buttonNextBase,
    path: 'buttonCompleteSelectFreqPersonSection',
    label: (t: TFunction) => t('selectFreqPerson:buttonCompleteSelectFreqPersonSection'),
    conditional: defaultConditional
};
